// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xTwY7TMBD9FWvgaDVhFy45okWiiIJEj2gPrjPNGiUeM+MUVlX+HY0TqJa2cEHkYjsz",
	"82be8/MRPA2JIsYs0ByBURJFwXJ4Wde6eIoZY9atS6kP3uVAsfoiFPWf+AccnO6eM+6hgWfVCbOao1K9",
	"YSaGaZostCieQ1IQaOC1aw3j1xElw2Th1f/ouUU+IBtc4nbBK6TnouYIiSkh5zBr4alFXZ8ClWRTYhb2",
	"xIPL0ECI+fYGLOTHhPMRO2RlN6CI664BnUokc4hdGU21CYwtNJ9hafQT5X6ysMHzWcXFdkff13fnfbZz",
	"yKzv/trshHJfJAxxTwqYQ+61bEM8mrePCbknSmDhgCxzl3r1YlUrX0oYXQrQwO2qXtVgIbn8UIaseurK",
	"JpHk80E/ocdwQDHvth8/mJ0TbI1WmIW8QEHn4ot1Cw28Vzz71ME3s5t+hy5uM9+cGBm9R5H92Ou4i+Ev",
	"eeoXbKVJJ6P+OVeTpqJeNZSL6vAi1zxyFKMKq4UCReN2NGaz3IEJWbDfn1He4BXC/+T5bPDS27mmXvl+",
	"BAAA//8tJV09TwQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
