// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/moru-ai/sandbox-infra/packages/db/types"
)

const createSandboxRun = `-- name: CreateSandboxRun :one
INSERT INTO "public"."sandbox_runs" (
    sandbox_id,
    team_id,
    template_id,
    build_id,
    status,
    timeout_at,
    metadata,
    volume_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'running',
    $5,
    $6,
    $7
) RETURNING id, sandbox_id, team_id, template_id, build_id, status, end_reason, created_at, updated_at, ended_at, timeout_at, metadata, volume_id, volume_mount_path
`

type CreateSandboxRunParams struct {
	SandboxID  string
	TeamID     uuid.UUID
	TemplateID string
	BuildID    *string
	TimeoutAt  *time.Time
	Metadata   types.JSONBStringMap
	VolumeID   *string
}

func (q *Queries) CreateSandboxRun(ctx context.Context, arg CreateSandboxRunParams) (SandboxRun, error) {
	row := q.db.QueryRow(ctx, createSandboxRun,
		arg.SandboxID,
		arg.TeamID,
		arg.TemplateID,
		arg.BuildID,
		arg.TimeoutAt,
		arg.Metadata,
		arg.VolumeID,
	)
	var i SandboxRun
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.TeamID,
		&i.TemplateID,
		&i.BuildID,
		&i.Status,
		&i.EndReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.TimeoutAt,
		&i.Metadata,
		&i.VolumeID,
		&i.VolumeMountPath,
	)
	return i, err
}

const createVolume = `-- name: CreateVolume :one
INSERT INTO "public"."volumes" (
    id,
    team_id,
    name,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, team_id, name, status, total_size_bytes, total_file_count, created_at, updated_at
`

type CreateVolumeParams struct {
	ID     string
	TeamID uuid.UUID
	Name   string
	Status string
}

func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, createVolume,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Status,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.TotalSizeBytes,
		&i.TotalFileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
