// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/moru-ai/sandbox-infra/packages/db/types"
)

const createSandboxRun = `-- name: CreateSandboxRun :one
INSERT INTO "public"."sandbox_runs" (
    sandbox_id,
    team_id,
    template_id,
    build_id,
    status,
    timeout_at,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'running',
    $5,
    $6
) RETURNING id, sandbox_id, team_id, template_id, build_id, status, end_reason, created_at, updated_at, ended_at, timeout_at, metadata
`

type CreateSandboxRunParams struct {
	SandboxID  string
	TeamID     uuid.UUID
	TemplateID string
	BuildID    *string
	TimeoutAt  *time.Time
	Metadata   types.JSONBStringMap
}

func (q *Queries) CreateSandboxRun(ctx context.Context, arg CreateSandboxRunParams) (SandboxRun, error) {
	row := q.db.QueryRow(ctx, createSandboxRun,
		arg.SandboxID,
		arg.TeamID,
		arg.TemplateID,
		arg.BuildID,
		arg.TimeoutAt,
		arg.Metadata,
	)
	var i SandboxRun
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.TeamID,
		&i.TemplateID,
		&i.BuildID,
		&i.Status,
		&i.EndReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.TimeoutAt,
		&i.Metadata,
	)
	return i, err
}
