// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSandboxRun = `-- name: GetSandboxRun :one
SELECT id, sandbox_id, team_id, template_id, build_id, status, end_reason, created_at, updated_at, ended_at, timeout_at, metadata, volume_id, volume_mount_path FROM "public"."sandbox_runs"
WHERE sandbox_id = $1
`

func (q *Queries) GetSandboxRun(ctx context.Context, sandboxID string) (SandboxRun, error) {
	row := q.db.QueryRow(ctx, getSandboxRun, sandboxID)
	var i SandboxRun
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.TeamID,
		&i.TemplateID,
		&i.BuildID,
		&i.Status,
		&i.EndReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.TimeoutAt,
		&i.Metadata,
		&i.VolumeID,
		&i.VolumeMountPath,
	)
	return i, err
}

const getVolume = `-- name: GetVolume :one
SELECT id, team_id, name, status, total_size_bytes, total_file_count, created_at, updated_at FROM "public"."volumes"
WHERE id = $1
`

func (q *Queries) GetVolume(ctx context.Context, id string) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolume, id)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.TotalSizeBytes,
		&i.TotalFileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolumeByName = `-- name: GetVolumeByName :one
SELECT id, team_id, name, status, total_size_bytes, total_file_count, created_at, updated_at FROM "public"."volumes"
WHERE team_id = $1 AND name = $2
`

type GetVolumeByNameParams struct {
	TeamID uuid.UUID
	Name   string
}

func (q *Queries) GetVolumeByName(ctx context.Context, arg GetVolumeByNameParams) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolumeByName, arg.TeamID, arg.Name)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.TotalSizeBytes,
		&i.TotalFileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolumesByStatus = `-- name: GetVolumesByStatus :many
SELECT id, team_id, name, status, total_size_bytes, total_file_count, created_at, updated_at FROM "public"."volumes"
WHERE status = $1
ORDER BY created_at ASC
`

func (q *Queries) GetVolumesByStatus(ctx context.Context, status string) ([]Volume, error) {
	rows, err := q.db.Query(ctx, getVolumesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.TotalSizeBytes,
			&i.TotalFileCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxRuns = `-- name: ListSandboxRuns :many
SELECT
    sr.sandbox_id,
    sr.template_id,
    ea.alias,
    sr.status,
    sr.end_reason,
    sr.created_at,
    sr.ended_at
FROM "public"."sandbox_runs" sr
LEFT JOIN "public"."env_aliases" ea ON sr.template_id = ea.env_id
WHERE sr.team_id = $1
  AND ($2::text[] IS NULL OR sr.status = ANY($2::text[]))
  AND sr.created_at < $3
ORDER BY sr.created_at DESC
LIMIT $4
`

type ListSandboxRunsParams struct {
	TeamID     uuid.UUID
	Status     []string
	CursorTime time.Time
	QueryLimit int32
}

type ListSandboxRunsRow struct {
	SandboxID  string
	TemplateID string
	Alias      *string
	Status     string
	EndReason  *string
	CreatedAt  time.Time
	EndedAt    *time.Time
}

func (q *Queries) ListSandboxRuns(ctx context.Context, arg ListSandboxRunsParams) ([]ListSandboxRunsRow, error) {
	rows, err := q.db.Query(ctx, listSandboxRuns,
		arg.TeamID,
		arg.Status,
		arg.CursorTime,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSandboxRunsRow
	for rows.Next() {
		var i ListSandboxRunsRow
		if err := rows.Scan(
			&i.SandboxID,
			&i.TemplateID,
			&i.Alias,
			&i.Status,
			&i.EndReason,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumes = `-- name: ListVolumes :many
SELECT id, team_id, name, status, total_size_bytes, total_file_count, created_at, updated_at
FROM "public"."volumes"
WHERE team_id = $1
  AND ($2::text[] IS NULL OR status = ANY($2::text[]))
ORDER BY created_at DESC
LIMIT $3
`

type ListVolumesParams struct {
	TeamID     uuid.UUID
	Status     []string
	QueryLimit int32
}

func (q *Queries) ListVolumes(ctx context.Context, arg ListVolumesParams) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumes, arg.TeamID, arg.Status, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.TotalSizeBytes,
			&i.TotalFileCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
