// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get.sql

package queries

import (
	"context"
)

const getSandboxRun = `-- name: GetSandboxRun :one
SELECT id, sandbox_id, team_id, template_id, build_id, status, end_reason, created_at, updated_at, ended_at, timeout_at, metadata FROM "public"."sandbox_runs"
WHERE sandbox_id = $1
`

func (q *Queries) GetSandboxRun(ctx context.Context, sandboxID string) (SandboxRun, error) {
	row := q.db.QueryRow(ctx, getSandboxRun, sandboxID)
	var i SandboxRun
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.TeamID,
		&i.TemplateID,
		&i.BuildID,
		&i.Status,
		&i.EndReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.TimeoutAt,
		&i.Metadata,
	)
	return i, err
}
