// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update.sql

package queries

import (
	"context"
	"time"
)

const endSandboxRun = `-- name: EndSandboxRun :exec
UPDATE "public"."sandbox_runs"
SET
    status = 'stopped',
    end_reason = $1,
    ended_at = NOW(),
    updated_at = NOW()
WHERE sandbox_id = $2
`

type EndSandboxRunParams struct {
	EndReason *string
	SandboxID string
}

func (q *Queries) EndSandboxRun(ctx context.Context, arg EndSandboxRunParams) error {
	_, err := q.db.Exec(ctx, endSandboxRun, arg.EndReason, arg.SandboxID)
	return err
}

const updateSandboxRunStatus = `-- name: UpdateSandboxRunStatus :exec
UPDATE "public"."sandbox_runs"
SET
    status = $1,
    updated_at = NOW()
WHERE sandbox_id = $2
`

type UpdateSandboxRunStatusParams struct {
	Status    string
	SandboxID string
}

func (q *Queries) UpdateSandboxRunStatus(ctx context.Context, arg UpdateSandboxRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateSandboxRunStatus, arg.Status, arg.SandboxID)
	return err
}

const updateSandboxRunTimeout = `-- name: UpdateSandboxRunTimeout :exec
UPDATE "public"."sandbox_runs"
SET
    timeout_at = $1,
    updated_at = NOW()
WHERE sandbox_id = $2
`

type UpdateSandboxRunTimeoutParams struct {
	TimeoutAt *time.Time
	SandboxID string
}

func (q *Queries) UpdateSandboxRunTimeout(ctx context.Context, arg UpdateSandboxRunTimeoutParams) error {
	_, err := q.db.Exec(ctx, updateSandboxRunTimeout, arg.TimeoutAt, arg.SandboxID)
	return err
}
