// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a2/cNtbwXyH0vh+2gGK7SXbxbID94DhN11s7NTx2+wDdoKClMzNc61aSGns28H9/",
	"wENSoiTqMuPxJanRD41HvJ47Dw/P+RJEeVrkGWRSBO++BAXlNAUJHP+iUQRCXOTXkB1/UD+wLHgXFFQu",
	"gzDIaArBu1abMODwR8k4xME7yUsIAxEtIaWqs1wXqoOQnGWL4O4uDGjBfoJ1/9D282ajXpUsiXsHtV83",
	"GzPLY+gd0nzcbMSCLlhGJcuzE5YyqRrFICLOCvVb8C44pbcsLVOSlekVcJLPCZOQCiJzwkGWPCMFcFLQ",
	"BQShXtUfJfB1vawEx3VXEcOclokM3n1/cBAG85ynVAbvApbJN6+DMEj1jOZzyjLzV2iXzzIJC+Ct9X+C",
	"W4n47+7hqOQi52rJQlIuiVwCSZiQZM7ztGfZWTXcMAAFzeKr/LYXK/X3zRAjgaa9g5qPm46YFgmVMDBq",
	"1WCTke9UY1HkmQBk17cHB+p/UZ5JyJCiaFEkLEIs7f9H5Iiherz/z2EevAv+334tA/b1V7H/A+c513M0",
	"UfqexkQtEYQM7sLg7cH3Dz/nYSmXkEkzKgHdTk3+5uEn/5jzKxbHkOkZ3z78jJ9ySeZ5mcV6xr8//IxH",
	"eTZPWIQY/etjUNEM+Aq4xeSdpXIk48NfZ+ewYELyNaoknhfAJdM0Tm/EIWocpRnirsQ5/HVGdAPyE6zJ",
	"8Qcyzzn54eic0AYRBWGbnUI1tpo4z/zD6m/kZgkcUJKpUblZKWGCJHlEJcQ9Q88g4iCrxfvn0I3cHUxf",
	"vv6hPerFugClPKqFdgaCTEn539Qag8+hR37VEuk3/TVso8G7QReg9bj51X9AE9phnLJspqX0TyxJzkGg",
	"cmqjfE5ZAvFRXmYeLfmp0o5G3oMgckkl0b2U6rlmSRJ0dVgYqA8bDSxK3Ny8TJI10b0Dr3J0IebOEjY2",
	"8/kuDN4rc+QkX/yQeck9gRUkY1x2ki9OsN1dGKQghDIJOvs5yRfEfCSWtz1EJCQU3c4zCQVhGVI9GlCk",
	"4DmSKAeluBDOqNzzBQHcio9AWQpC0tQzwYX9pADeHqgyVGIq4ZUaJRgl02qqGiShgWYF9pmkshTnQI1M",
	"a4FeI8X8VZlOv30OPZAF3bINDoEzEK6nCAO04MbQ2SSJirEDyjldD+L41OD3hslld/6QRCXnkMlkTTgU",
	"OZcsW5A8S7SQQVlsemxIGQ7DjWLGLl5h4ejssof7js4uSZRzELg03IrmwsBntw5YqqHSbRlE0giaLp4V",
	"qeSl9NNkXkpF9wKiPIsFmq24GgNJojoTOpfAyc2SRUt3qUQs8zKJCdwWjMPgwg9GpYhdpU+QHnFQRHdY",
	"n8S6u4xMGznCe/o4R6QahWAnrSSm8GAYMI9GPo6VtpkzLUwVfNw53KHLknmVZ0rF9RjT1LOcUnHNssUH",
	"kJQlQvXXVnZHwNMUelbUlVz+483FEohWBga8IwO1cIq7xcXZGcxeQwddn2sEXwBND8+OjfGwHX4Pz47J",
	"Naw3R62Z4D3OTZPk53nw7rdhnKj1XgpFzJ/DICuThF4loI81k2nFrHcKmVz7jKpzekNWNCmhO2BngIQK",
	"eSnAs64TKgyvyyUTFRBvqCClQKHnBWJzz09C2b3b9dGibmhI0BBmkxI/MHF9CpKzSHRpMIYVizzr+YC/",
	"E0vpbSDMWQJiLSSkF14L9mP1nai+5C+wt9gLCdzKtyG5nYvvvDJD6ZWznPmUy6n6Rgr10YIpZrhnD+NL",
	"mrxfS7vBBl+pb0QUNAKlI66wlUunLJN/e+u1PBXR9IyqCHCbQdtqtt5/aBHTAbW7kMZeLapn7L9w+t6D",
	"USauiWD/hbZ6Vms+Ze83VXZh8EO2+oUar2McMzUPTc5a5OUu4YdsxXiepUoLryhnis981kKX7H/IVvEv",
	"wIX3oGc+WLqAbBUTXmaZMpWMAdw7dhjo825XOOexh66xMcFvHnB1QdRr9ulZxzjcTOTaXx95nh6ndAHu",
	"eTtmauyUZVTqvaS0KNSA+vTdJ6bcU3sYLKKir+GPR2dOQ17N3NMaMuA0qXrchRa260/GeaZ2fRcGeQYT",
	"dJK7zLtwuK270tG27XUq+LoDdIhCAFdceRhFilX/JXzUONNtiGlE/jX7+RPS+I9HZ4/gEVBYnOoR8GzH",
	"Z6u24dQBS0GFuMm5RwmfmS/qcFWKWvTwmpp2DoFq7M+ewUsB3K+BL82X6Uv1A7WaIazh4oNqr43QAa9S",
	"7hD/oiyiMw5zduuBM/6Oho0SeboHWTUFoz4g5LzPlnLmmZVz7zz693vOUwxvAk+mzEJHdIYkBtCdcdFm",
	"PIFsIZcecxB/H15in2I2C27OEHrw4oOhEionTEiIe4+zNGHUoy4P1c/Vis19g9fOTxhkUl9VxFBw0D5N",
	"Y8GOmeu6t3fcoqzO+kOCtPIJ3IVKFTkmyFAvx1i5U9zbexAiN0toqHFyw5LEc0YfPAxB04QYdIE7TVGJ",
	"pzlfj2/o1LbDPpLGVI562w1NnNrm7UuyMeQNGDZ4fQebQJUKYjpNhqqQiianbXKGbTuXa2NbtK21J0e7",
	"bJhorNwceMZFtHtp5142Vhzkgs1hAIcIGiRu6dYCoklmyPrW0ev17qJ3E1WNdtEm+UI4qiyGq3KBd67z",
	"PAiDG8pR0aHt6NNuJ/lCfGAcIuk1lKtPjsfWuN6N3+sKzEU1AtMuY57zG8rVL1c0usZ/dmYPg9tXqv2r",
	"FUX1J1THxno+VqM0fn5fDWk2MMtL7juS6t83XLrCeM4pqu9CoUWgF3368vWsF84w9a9nzoB3YXBKoyXL",
	"4Fghq3ueKMpDHi2ZhEiWHPzuU+q0sBvN9BnAJ5w/0pQla/9Qc/w2YZDTPPZRpxojVZ+mDvHJa1XVw2SO",
	"h8M/VvvwU23QWWdrvrADV42I2wugqXZ6eKQf0JSk+NG43Z2bh66j2bn+GFatnQsRM8cmdyLOjctl5jOS",
	"BidRNpnqpv1ef7EucMGyCAgUebT8rnVu7XF2oKHjd56aiJOmh85EF0Bsl2PO3Qu2goyogfmKOjd6OkBm",
	"8AqoCQe7JERvVAz4HDr31qdHZyTKszlblFwHI3Q9Dj1ev9paP3VsgPYFjvqyjVPl+9f/44P9J7gZvBa4",
	"r2u8BXMc7rOed8BCTfKb3xGPGcjf9QQ+izXJbyoQyLxayRKI7bxHflWGhwCpGsxpIiAkTJIrWNIVWL2e",
	"AlHWSAERm69ZtiAxZOufS+xzsIf/7R9YKstA3uT82mB5r97yVZ4nQNGIo6XMz2gpoHEzqKfvhq7kKVUn",
	"yyRZk0J1apob+vIIbRNzxeObEWr32Iixic2U0agJe9DGjIp7mpcGWBN7ftKtjxCyaPBB5FVfM/yd0CQh",
	"xvEb5WlaZjYACAVtx1p1wLWZUWgpePBc1LgmtGF0f/WJbUVWCVt5faNGiu7d9zaw3p/htqG7od3dEtT8",
	"bTyaLbskKYUEPg3qprHXDMhTb0jkEf5uB8h5tAQhOfope2+sPlo/yEh4h7H78Rp7qhtfd5npqBDYZBZR",
	"9Zk207TLsj6zKm0ak4MywWmqZYO96xnqpcjBXgs1omU39yBkeUrj3p0YMG4Qs2Od93nmgqgB8x5/u6hO",
	"mhgpMT6naUhmdvIWl/tn0X7T40xImkVeiWW9wMy0qR1ao5g34RwT0KeDYdBem3g3Msx/bclhY6TxorG7",
	"6dARHtWyW/iuybHLek1270FevbdKxjSZw4o27T71CDgaLSHGAB0Pt58wgcJJt9KncEFY3KK9Kgiox1td",
	"B/q8yNMXefoo8hQGqHlMlE6KaWs6rT2k/iIGJ4hBLedcGTQuCH0Sr5KiPtnnhHe0w9Jj6yEQHeeGOtQh",
	"XR6dXQ7xbdWOVCF+E9Vx1VMfknvCJw4x8KE5k3a3bhqj4V5Y+AI/6nc5dbDi5kZGVJRnwCPwmhYK4Grw",
	"EqM6C91Oh7JOGTtm4lr4wnGkjo02uNTRnzRaYhTMflpHx0zlbjcqyBuvquB/MRpKk2kC2wZZutdlf1jN",
	"J2dse+O4dXBNg9h7KLOB2u4CPfcBDoAs7ixPzir51Y6+xfjepvSr765prI50Macs037pSMfC6j/KbAk0",
	"kcv1RA92vZBzM3L9y4d6jvrHI3e2+ufLet7G9o6WNFvs7lQ5Gi+4uVJokYEZQO3iHESZDt3KNj1Gw0p8",
	"Rz6jJ/ZY3IXBV3dJHecpZR6V/54KIPqj8/6n8k1yOp+ziDBhfJTsKpkU/gnZqh213QKIG42NYgtldbaK",
	"mx6x3d5R7+rS+PGuZsPA4GAQmvhz7e1ToDT4yhbVHCtGScHz2/XeOAa3uBFuX+kaFuk7cL5EczwBUz5C",
	"8Mgz5PqXyJSXyJStI1PM3k/yhT82Rd8oNy/ICc1ikrAMOodJ/NEf48KyweeLT/TEEBfchEPPg05YQSbt",
	"O4cJ1KRGqrrgYwkwvse+MPk+r2J9/3zfN6JPBOQadO6bTgOQFvBdKPtjfy1T4QJXeqf25CRkrI1qIWPg",
	"XNOnksm/I9s4f0MWe4On6qWI8ZelzRMdLzH4RMdvdQXgpAN5mww9h/LELK1DAfefsztdC6smMs2Bg4O+",
	"U0enTHsKYnuMaovGJN5wnlM3AGaquOr3FH3q+oimvfWIivJSQHwW9byNHfIIzZOcym54jJbo6GToc8DE",
	"+Kyn9+1Rv/tFdfS/nMOXQr0Ol0GHzuBSB9xEg4P6V3k64hjqH/LPGdS1QaiVY1w4RF3jwkG1Q0cusTqy",
	"oRlB4o8s+tn3ltteZmALiMnR8YdzcpXk0bUgOSfHZ4TGMUcPuja2FxxNcH2I2COHpl/diiY3dC2IpNdA",
	"FNYhBgXDfAVcD+y23tvo2g8XeVZeJSy60Ato+HB8lDXTwU2ENSQguTw/EU5Ma30Q0s/+UcA13774A55M",
	"wFQ/XGPI2MZg3QgoKRXX5zoy8J+58CzFgmCZC4mPSYwRjUe0K6gPUhhWZABkYg2FV1d0DKeGhe91xkJX",
	"B1XuWH17hk958NHwgN0A4lcml70PbRu3dn06ctp5TGnBu45jsxpf8d4F0NTDa5iczXN4NW+jrStRqt6+",
	"VAHigyXo9hC/LkEuoe5uz0GGA1pDOmQ6HujUt5o66df4Oc03QucEZtKEmcdbBljuri1kXx709zro//Tv",
	"8Q31eHNC7CgoPcozk8tk1h8KcLEE57qz7uLEBrTYfYKJ60bonHsFqjcFk/ZbYO5Dbb1MMn1fzLQxM81D",
	"Bx4cWcpDKdB1bqTGid16n65+ttsshT9GaZr0ML1HRIePl/Ta9PqNv9zvbYc+fzv4PO7TDRgMBxs9JyJe",
	"mg5BJdVUZzmNr5z0p2PQVALWSWpm3o0pVtZvLYZuFq7qDFpjEtMC3Em6te0dwohWrL29DejVjtMnUo3b",
	"P2Td1puvUDsr6E22MbCQKO6nRbe4SSjwuDNmC5plMkF0e3XIwJOMc7K5WnvsNMdIFAoq2/JhGy4DjoGt",
	"vP8+aiyLeAua12jUXbf0vbrXCHXa5Am3BQaZLru623AZrE2pDfw0hGaTG8JKWDdFkSvgUd50pfwGAhKb",
	"TjFVH1SWabG8jSB7fLkzZxkTy812ZftM3tY2AkbcR1VNZsF6U/fnv5rlqjjQXn7y8GSHEz6yBC6LJKce",
	"nig4CG8Moit/5yxB2UsTDC0jppN9OYeBqV6RW3KPVXjJE+faHseuPVUlrhMTaY7Cya69s2H/4+kt2L97",
	"Mp2aG/R99RKfiOpmZ2eJQOs7nAkL2MhY5VVS1NEFNrKo3pfRdqU1p6myiq/8F1KNNZ7kC3Fusq17r/Se",
	"khR892udHRjv6QMEGW0TDJRH18AV13vujKpvjluhf/pttAEKsKPUc+bE2FYSLSG6xmgbmmHCKbiFqJRg",
	"ZV1latWhmL3CAl0W3rnwXL2jWXbswXTw00dIv7x+HqS0Df53DC297V5AvXkB1DCgkBF89DTPq/QtQ6/s",
	"XSvlZpkn1hCrDQocCHmMlxnhsKA8TkBUsO43XuY2SaIHCOpnm+ONCkLJFRVdodXPtHNfAsYh1HQzNppR",
	"XKdW2xlsVnGPdX574lJIKEYTu9sXcKrt0Hx2lkmq3OJjJqHwavLOtaPPVhp5CtJZmr2FxL/1NeQNZeZt",
	"hn0p0p8Myi7hBBY0Wr94Tu/jOX3xe774PV/8ni9+z3v6PV0jyhia9nzaa3A+qIR+eMn5eMzyuH6Iim58",
	"uJ2NVuRpKntbmqf7RJuP+igO+aJMlayqXwKq2TchBUwx/08qPGlz1a8WZNisCrh0ZurayJsfAdRQO7H9",
	"h9NH96/al83ZxeklyoReh8xj0fmds6RfmVzWiU0eW3YM5J8waVQ8nqCNzG19GeRLsvIoptVT2iUvNsbz",
	"tjE64r/fgBg3GrTy0AJmi6RwcKOTq1p22zAznE3qx+R6phhQz+W8djwsdUL1K6Ac+EcLOU1jv0u37ivS",
	"FjarZ19KWVS1AxsDYlnVJdAYm5vCqv/7Chu+umhmrzThmGoc/NfYGGfHr35yYVD3n5UFvaICvp+yFtu4",
	"fzm2xWvE3NTRGtxoB1OoYOYCTDKpxENwmvPSZidTmHXSw7wLDva+3zvAQhoFZLRgwbvgzd7B3gEGLMsl",
	"InJf4+kV4kkrCm8sti5YRSjJ4KadQVQRIUaqHsfBu+AsF9IhD2EK4IKQ7/N4vbNCpK08qK2IZ3NabRTT",
	"fb3DwraeAm2+Kred0msQN0pOOvV2fbNVy99XjepKrsNtVSOXbfHE7yPr3z6rI76kC0wG0iQEZPwmcex/",
	"aVQGv9NEkoD0FohSvxOaDdOKbuZSy2Gr+LhbvrzHcVE32W+WLle7a1HA25G32Xo/90OSqSg81vbtkyBU",
	"Cc99pe3F/hd9E3C3X8Xi7mNh1V4Z8BNLEuE+tnDLM+FbDYYpV1F4eYQCSng19QVOXIWl/qTLubZQ7QmA",
	"1nm2tqrhPRZf2iWV3dVM7imL6yui3C1HW8P6edJhW29rGhRlmlKsAaU27KEZWpmcllrVOJZKC/bqGtaI",
	"iAX0PVJSg+JjEmPRiA7V/QhSmwNaCd0DvRMPJpVx1r0FGMa1rU3g2dQTqwivCdMSNBZdyk6dYD64+/NL",
	"CgdpD2I5uJh6EsOhvQCPsGs8A3pmdsNmROGy9P4Xbc5OtB+GacWYD5paDs24mxsNtuM0e6GBnK/dXtiY",
	"u6mMPH5AfTgdQ9eZ6rxjbO1ePHQO2pMkxMEIoZgj/5+EUBTH65SAvSr8n/hZxxn4FLf+HkwBtPG66jxA",
	"FXw3gy4ieT/LY5hgdehmnkV/Mh92Y2tMu6/FxP1YnHJ7i0Nv6NGUit9m9FmCuLD9LzrJ7l0vZn4EqXON",
	"mlJYfsR8sql6N5M4JsPvXbhJrko8pfxRAj4vNMeURiLgZ3EycTKjT6aXKi/pV3QcaZNWr5mKCUuJqCJv",
	"qE3B2jVSd0FSD6TCOhlY74wOG7VtDG4tBPBeBIf4GjTXdLHSSLcwLOttinQ3YXdHvLgvbAfdGFViIxQN",
	"+rZU5mTOEhvfVh+TsSo6+TeWjP0HvYr+XR4cvP4bLYp/FDyP/x18t0d+oNESzQuaxbrkliBpKSS5AnJ5",
	"fkIgi/IY4r0egVQl+3Pl0a7lz4bqrJVX/n56rYs8JMaDKcR48Ij60Lmz+O2zUjRbG2HNRB8jh3GbMwUT",
	"FLYu1roCzyXyBzqXV2h/3EN5Y9quRHTzTPafxv8kRNUQn/tO9Yt+MepmpdchQdOE6WldmWBIph7laUpf",
	"CVCNFGqSZpkLcvwBQ30X0FhJEAZwWyRY9cqEn/hEpBnkdxaLQf9yf3RESm+P9cfvDw5awiwMyoz9UYJp",
	"gHT+oAafNxvR/USqzkeS1sUC/qSs8KXKyzro2dL+cCeblM+lVaFp5uR63czErLPETnRrtQSdvX14/lbf",
	"QynP3pNmrTiv1gTPbP0y7IEQuHOJsM0pUNTFf/40ZNHL8/umEkf/9ek5wk5UxBPrLFN75LiZ4o8JXSEi",
	"xsKnNtkd1/Uo9sjFxYlqgoFccCshMwb+gMFWEaGp33FvWty98WdWtpEBePAUBqB9Km+T/92FT2WKGop4",
	"NFP0G+Vb+9C7V9w7eaXFNFl/oltuzWOh952csrqkJxt3b6F7wjKSsiRhJttYn1uy5ALtYY9P0kZsDley",
	"7Xg5TBHwOsPcSD1+37ISpmub1auqa94oQ7pbu0bPaj6Prdg3Zcw4RCbl4jR2VZj+UPXygOKj9uxcrXVK",
	"cqKWQv6i05GTnBOdj/w7VAJZLus4mtDARwfcKPj1eXHcLOobCZlmJvrHsDKQMbaxMTTzvQgsJbDGztyu",
	"zKqL+00QW73n7XtIrirnoZZa9SMUyqsypVj7fUWT0KlOFWJTne+3zqXYJ8JsEv97SDAvZ2EuSlcATdga",
	"ZPF2G9tsyZ8fI6KplVV4W1esy8iP4Cj4Rvm+sNXm/McLLEbXylQ95Uygi9g9tntBn3AatiteYkQ0c047",
	"D4n5twd/n9L2718ZlXCYcxBLEEMHUWzSYEt9klQmJpPCJGLWJQQnktF5Ne/THC6bb2HiUi/YE1lmvrTE",
	"sIVDbZ5eQyEJxSKKtfR2zcw3fxu3M9upHybew7bEqIbsIzldngEFK95vku9wemddq3ML2ac7PkN3SKv6",
	"6PO9D+t3QrxI7Q1o3qns6pfZM5Buedh2Xdc9cuGvYUhurehybnlZnb3eEO8eOaJJgh6GJRPKSFvmMUnL",
	"RLIiAfO+M18Bv+FMmqeeFxcnoa4yjQOWQncHYnPJO4WWRG31q1ZYi1opmBSoKE3CSLs1K7unOjUvqoq5",
	"T693GhV6229P1eZqVVLjw4WXyXTUq5i6lSknle7tpo1Xq/y8E/0kDGlWdTrN6H82qx1fVU17suI9kF+Y",
	"D48ZbYMvTe8ZZKM39HiXue2nx0NobASAqd8cVNUP4KZ4VNwgBufFvB+L+oHbtv4U85ztxZnybTlTnPou",
	"9/KkyLoWzAO7Ud5Mafvm2QjkUQbfT+ntIJMjDZnLCx/D28w2OorJUuQ0MXBKb18kwbOXBGFP/VCZKybk",
	"DFbQoBIMujXxZD0hthwzgfSHjtlEjnXBnt9Ft2KPLlT7O8eaPY/7SuCU3rqy60VW7VpW6aDbSbajbeoV",
	"OfXHlpjxUWb1aL6PEScnBP782DarCVK+t91q4fWEgYhbW7P16puB3sOestY77IFob5eaHsLD5U1kP8nP",
	"9XrnazA5cHvcXXUFEBpFUEh7LfHsolx3QUoNgaQMKJvVaupz7R6S0i0qorpoZMva0Caquk6/emok+9rF",
	"o+1nKAOGVYeTdG8ATa4a2RGOwtHWBV2wDNfwCW6lyaa0SbcTDBV6UBvIk1RxQ0PIEiCTS7xjM7ndvsYg",
	"+JbuGcwJ0K9kVLcHEQgPp6yaWT63TgzQyZPYmxzg+b+keGQD5hy0OqbZRPPl6yCsr9cK+gYsm30tive/",
	"mPzNd5vcPesSFm5liknEqHXI+zph9APqV5uW2qMgX/ulk0b2klbVmb9dXI/Hf7eScfeFgY8heaug8C0R",
	"/RJA/hUHkHv3AitINhn0BDt4QDvLSx7BJOzPeZ72eYZxlI12qSd+YFdlf4G/7ax1h+Wf53W2X1pOtfV3",
	"IT/r6pBTJWhfkp4xCTqzxR2fRoYeZzHc1lUCjECtKKSXjfDE10507+PxfCF+ns8F9Aitg42DPr4Vsbq1",
	"9Hs0UYOFabcSMS9yRcsVLB+y/2VJxXI4zxfNTC1hkrDs2jq0KNcFhxVqKcsczqRr0N+mWm0fq3on95Q0",
	"nkzFSz1s/2XgSH2VSbcv3z8MjTvVpnvOiC5eTCHo3P6ING+w9A08/ng4/li93iQ91WAmlV9ef8uJqfre",
	"WtYLvVqTPAOSc5LmXCc1Q0hMSvwitabe7sXUTBrR3q5NI+QaCzcoLfk1+cZfsng9ZWjp6nUzSmD3172/",
	"vH6KC99fXj93Z6eBxDeV8WtE+2zlJN3UJerQ23Nwij4wudtq2NOJ/Xn5ZHdBWG/6RNiWAuvNkwisN08l",
	"sLoFQV9kl0tiOCBfWVlR8sQUFxPv9vdpwfbSnJd7LA+cEb7UsXB1KNiXVuq/5o8Yt+f+3Siy436w2dDv",
	"Pt/9XwAAAP//6haTXpTlAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
