// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a2/cuJLoXyF090Ny0XY7j3NwJ8B+cJxkjnfsjOG2MwvM8Q1oid3NtSRqSKrtnsD/",
	"fcEiKVES9Wq3H0mMA5yJW3zWi8WqYtW3IGRJxlKSShG8+xZkmOOESMLhLxyGRIgzdkXSww/qB5oG74IM",
	"y2UwCVKckOBdrc0k4OSvnHISBe8kz8kkEOGSJFh1lutMdRCS03QR3N5OApzR38i6fWj7edyolzmNo9ZB",
	"7ddxY6YsIq1Dmo/jRszwgqZYUpYe0YRK1SgiIuQ0U78F74JjfEOTPEFpnlwSjtgcUUkSgSRDnMicpygj",
	"HGV4QYKJXtVfOeHrclkxjOuuIiJznMcyePdqb28SzBlPsAzeBTSVb14HkyDRM5rPCU3NXxO7fJpKsiC8",
	"tv7P5EYC/pt7OMi5YFwtWUjMJZJLgmIqJJpzlrQsOy2G6wagwGl0yW5asVJ+H4cYSXDSOqj5OHbEJIux",
	"JB2jFg3GjbxicZ6Qw+h3/hlGqsP/C3xHhx/QixWLv97c3LxEjCOYduJbiRlw3DpuVWORsVQQEBtv9/bU",
	"f0KWSpICZeMsi2kI1DL9H8GAUsrx/oOTefAu+D/TUhZN9Vcx/cg543qO6tbe4wipJRIhg9tJ8Hbv1f3P",
	"uZ/LJUmlGRUR3U5N/ub+J//E+CWNIpLqGd/e/4yfmURzlqeRnvGX+5/xgKXzmIaA0X88BBXNCF8RbjF5",
	"a6kcyHj/j9kpWVAh+RqORs4ywiXVNI6vxT6cfOqEipqct//HDOkG6DeyVhw4Zxx9PDhFuEJEwaTOThM1",
	"tpqYpf5h9Td0vSScgERVo3KzUkQFilmIJYlahp6RkBNZLN4/h27k7mD48vUP9VHP1hlRh1ix0MZAJFWn",
	"zZ9qjcHFxCPtSon0p/46qaPBu0EXoOW47PJ/iCa0/Sih6UyfFr/ROD4lAg7JOsrnmMYkOmB56jmtPxen",
	"tDl3iEByiSXSvdQReEXjOGiepZNAfRg1sMhhc/M8jtdI9w68h7QLMXeWSWUzF7eT4L1Si47Y4mPqJfeY",
	"rEjcx2VHbHEE7W4nQUKEUKpJYz9HbIHMR2R520NEQpKs2XkmSYZoClQPihzKOAMS5UQdoABnUDLYAhHY",
	"io9AaUKExIlngjP7SQG8PlChMEVYkh01StBLpsVUJUgmBpoF2GcSy1ycEmxkWg30Ginmr0KF+/Ni4oEs",
	"0S3r4BAwA+J6ikkAmmQfOqskUTB2gDnH604cHxv8XlO5bM4/QWHOOUllvEacZIxLmi4QS2MtZEAWmx4j",
	"KcNhuF7M2MUrLBycnLdw38HJOQoZJwKWBlvRXBj49OcOjXmizraUhNIImiaeFamwXPppkuVS0b0gIUsj",
	"AeozrMZAEqnOCM8l4eh6ScOlu1QkliyPI0RuMspJ58L3eqWIXaVPkB5wgiXROuepUc0a20y7FFX1Eb3I",
	"U/pXTuB6o/TtCRJxvkB61S8DdfWQknDV7f//iXf+vlD/t7fzy87F/zX/uviPXvTDMto3Ee2X19rmHkLT",
	"RvYIEH03RlKNgqCTPumGCJJJQD1qxWGkjsw51SeCQrI7hzt0nlOvBpBgcdXH+eUsx1hc0XTxgUhMY6H6",
	"+/Gnrh8tK2qKX/9d8WxJkD7RDHh7BqohFHZrLja2B+x14qDrokTwGcHJ/smh0YA2w+/+ySG6IuvxqDUT",
	"vIe5cRz/Pg/e/dmNE7Xec6E48mISpHkc48uY6LvZYFox6x1CJlc+zfAUX6MVjnPSHLAxQIyFPBfEs64j",
	"LIzAkksqCiBeY4FyAZLbC8Tqnh+Fslu366NF3dCQoCHMKiV+oOLqmEhOQ9GkwYisaOhZzwf43V7hG0CY",
	"05iItZAkOfOq4Z+K70j1RS/I7mJ3gsiNfDtBN3Px0isz1OF4wqjvhDxW31CmPlowRRT27GF8ieP3a2k3",
	"WOEr9Q2JDIdEHXSX0MqlU5rKf771qs+KaFpGVQS4yaB1XaHc/8QipgFqdyGVvVpUz+jf5Pi9B6NUXCFB",
	"/yZ1HUOt+Zi+H3tiT4KP6eoLNibcKKJqHhyf1MjLXcLHdEU5SxOlSqwwp4rPfCpPk+w/pqvoC+HCe1s1",
	"HyxdkHQVIZ6nqdL3jBbfOvYk0Jf2pnBmkYeuoTGCbx5wNUHUqrvqWfs43EzkKpGKsw7TOWuuOGGREjne",
	"8wSEoW5grEpG3A07SPwySy0FMY4iykkoGV+3iguw/jX753GM1CfQ4GmKtFnQq43Tv9sWACRt2Q69KBR8",
	"4JuXNTS18LbflgA3EmRMANZsoIZV7Gn33G9DMEAxFlBo69MI1WaOqJCnxsbpsQyoHYFtd8i9qiAUz5Uq",
	"bbelnxQGd6NQKliq9tYH0L1ZvUbv/jhLDhO8IK61K6Jq7kTNqJkwwVmmxtW2r7a9uTazSbAIs7aGvx6c",
	"OA15MXNLa5ISjuOih6JcjYH1Z2NCV7u6nQQsJQOUKXeZt5Putu5Ke9vW16kEgztAg3QE4eo42Q9Ddcb8",
	"l/CJ0Zlug0wj9F+z3z8D9n89OHkAe5zC4lB7nGc7PpKrw6kBlgwLcc145GMD/QVJptTF4pDiJTVtHQLF",
	"2BeewXNBuF8Mn5svw5fqB2oxw6SEiw+qrcpt80TC4opEX5Qqf8LJnN544Ay/g0auhLjugVbVE10LIsbb",
	"LgHOPLN87p1H/37HebLuTYBdiFroiMaQ9ihpjAuXnSOSLnynpP69e4ltGqVZcHWGiQcvPhgqoaIOJBK1",
	"GpNwTLFHz9tXPxcrNl5H7wU1piSV2mEZkYwT7VEwV6++e6bu7R03ywtLW5cgLSxyt+pEd3Xnrl6Oln2r",
	"uLf1Bo+ul6Sif6JrGsceC1mn8kWqum+nA8ppCtpnwvi6f0PHth30kTjCstfXZWji2Davu8r7kNehkYMT",
	"n4yBKhbIdBoMVSEVTQ7b5AzaNlzsfVu0rbUdVRtMqais3NzU+0W067p3Qw4KDnLB5jCAQwQVErd0awFR",
	"JTNgfetm8fpWwLcAR412kMRsIZyjLCKX+QJ8/3MWTIJrzOGgg0uP73Q7YgvxAVRq7w2v+OT4S4zjy1id",
	"L4kJVwFgFso649eYq18ucXgF/2zMPgludlT7nRWG40+ojpX1fCpGqfz8vhjSbGDGcu6zpejfRy5dYZxx",
	"DMd3ptAiwIc1fPl61jNnmPLXE2fA20lwjMMlTVuulWGW7/NwSSUJZc6J33mBnRZ2o6m+vPqE8yec0Hjt",
	"H2oO3wYMcswiH3WqMRL1aegQ/piWcpjUMc35x6rf2osNOuuszTdpwFUj4uaM4ERb6zzSj+AEJfDROL0c",
	"v1/TzeM4H7uP1oY70swxxiPp+DvPU5+S1DmJ0slUN22wfWEdUIKmIUEkY+Fy4E0eFB2/1d/EnVVNyya2",
	"h0R2OcZgtKArkiI1MF9hx5+uw+Q6HbBVONglAXrDrMNY1ogaOT44QSFL53SRc30jb5rKWszVpbZ+7OgA",
	"dfep+rKJNfDV6//ng/1nct3pz7qrT8frW9PzdmioMbv+CnhMifyqJ/BprDG7LkAgWbGSJUG28y76Qyke",
	"gkjVYI5jQSaISnRJlnhF7LmeEKS0kYyEdL6m6QJFJF3/nkOfvV3433TPUllK5DXjVwbLu+WWLxmLCQYl",
	"DueSneBckIpfXk/fDBxjCVY3yzheo0x1qqob2nULuolxsPpmJKVdt0fZhGZKadSE3aljhtkd1UsDrIE9",
	"P+vWBwBZUPhI6D2+ZvA7wnGMjMciZEmSp9ZQCoK2oa064BqnFFoK7rwXVZz0Npj2Hz6xrcgqpiuvUd9I",
	"0d3xln0b8NkV6qmYREocLq1zZ8Xir/gyfPX6zctddKq3KYxNF9w3J1gud73332qbVu8PlktEU0Gjcptm",
	"7qnCNXhgpopcygVEiM6R3Y7SvjPOVjQi0S46zoU0AcOAY2eMCYJh1H+TVE4n6sI91aOI6e4Ybd3Ipy43",
	"8PYcgqVENM6LmiYX50ISPoxOTWOv4sQSbyj5AfxuB2A8XBIhOVh2W53Tn6zlqCcczdyUIOxmqMdOd5np",
	"KDYyZhZR9Bk20zC/eJsimlTV704p6jTV0tS6dbt6KXKwHuDKK4PxNpeUJThq3YkB44gYQ+unY6kLogrM",
	"W1xroribQ2RX/5ymIZrZyWty0T+LtjQfpkLiNPTKeGs3p6ZNaQLsxbwJPxuAPh28B8JyoBu0m//qksO+",
	"LYGYguamJ47wKJZdw3dJjk3Wq7J7C/LKvRUypsocVrRpg7NHwOFwSSIIKPRw+xEVIJx0K223EIhGNdor",
	"nGst9v3Si/YsT5/l6YPIU9JBzX2idJCvuGrm95D6sxgcIAa1nHNlUL8g9Em8Qor6ZJ8TyVV/RhNZm4po",
	"mIPUNRjo8uDkvItvi3aoCEkeeBwXPbVZoSVSah9inKozaQP12HAs18Xji/Eq3zOWwdXjlYwwy08ID4lX",
	"tVAAV4PnEIWe6XY6SGLI2BEVV8IXeSf1Ww6DSx2tru5ZqsM0KQPhhnK3GwDoja9X8D/rjZpLNYFtgizd",
	"67w9gu6zM7b10W4cR1ch9hbKrKC2uUCPB8UBkMWd5clZIb/qrwXgPUJV+pXefhypK13EMU21JT/Usfv6",
	"jzxdEhzL5Xqgzb9cyKkZufzlQzlH+eOBO1v583k5b2V7B0ucLrZ3q+wNDR5/KNTIwAygdnFKRJ50+bGr",
	"NrbuQ3xLVrbHtfEoYH13bv2IJZh6jvz3WBCkPzrvFQtrLsfzOQ0RFcaqSy/jQZHeJF3VH2jUAOI+vACx",
	"BbI6XUVVG+J2vfrbcrM/nDN7EhgcdEITfi7towqUBl/pophjRTHKOLtZ7/ZjcAMfet0Jblik7cL5HP/y",
	"CEz5AOE2T5Drn2N5nmN5No7lMXs/Ygt/NI/2wVdDChBOIxTTlDQuk/CjPyqIpp3PrR/pSTQsuAqHlgfo",
	"ZEVSaZ80DaAmNVLRBd5FEWN7bHsR02ZVLD32d33T/khALkHnvkE3AKkB34WyP1raMhUscKV3am9OQkZa",
	"qRYyIpxr+lQy+SuwjfM3SSNvuFm5FNH/Er56o+M5hOvoiLemABx0Ia+ToedSHpulNSjg7nM2p6th1cTy",
	"OXBw0HfsnCnDXn3ZHr2nRWUSbwDUsRsyNFRctVuKPjdtRMOedYVZfi5IdBK2vOXvsgjNY4ZlM6BIS3Qw",
	"MrQZYCJ4wdf6zLDd/KI6+h/JwqPAVoNLp0Gnc6kdZqLOQf2rPO4xDHU87Popw+BGBKc5yoVD1CUuHFQ7",
	"dOQSqyMbqjE3/lis3325J6wzA1qQCB0cfjhFlzELrwRiHB2eIBxFHCzoWtlecFDB9SViF+2bfmUrHF/j",
	"tUASXxGksE4iomDIVoTrgd3Wu6PcfrDIk/wypuGZXkDFhuOjrJkOB0O0IgHR+emRcKKAy4uQTlMCAq76",
	"WsgfImZCzNrhGpGUjgbrKKAkWFyZZBz/YsKzFAuCJRMSnt8YJRquaJekvEhBIJYBkInOFN6zoqE4GSo8",
	"zdPBN/Uzq9br7+05FHwXmD98d5fyFjD0uhmVKXkGHOCnefqx6KL7D1ydkCzLxtyq2q+A5zp1SmGHLK5L",
	"mxtyy+2VPr6uK1qBOSAcyayruU/DqFiInctX9VZmPXtOJoVOgvvoYrGWzQJ+b8GEVWnL7FqFxZiYF+Ji",
	"mcuIXaddimwJtQ4fBC7ZKq88O9R+Y3j2ZzJj2AV2TDmzd+7mdKSp6bXO1TEDEX9QuWzNXFHxjbdposOs",
	"HkrXvG0hDqP9nhGceKQKpI71mIhMshFrsJeqty/3jvhgjw0P+8olKbtba4M5Z2pDOodBfzhh22rKlKT9",
	"1hDfCA07h0liah6VGmC5u7aQfc6Q0+oG++kT3Bjq8SZZ2tJjmZClJsPZrD3g5mxJnKCCsosTgVNj9wEX",
	"STcO7tQrUL2JGbV1EFKX6TvCoAvm82Wo7zLkoQMPjizlgRRomhAT4yqqJRNRP9tt5sKvKg2THqZ3j+jw",
	"8ZJem16/8Ur5NWXS5tUiPr/W8GsCBF32WmMAL1Wzu5JqqrMcxldOcvY+aCoB66Q6Ne9ZFSvrN2Bd/rvL",
	"Mq9mn8S0AHdScW7qqes5FUufSgV6Yy8mWz8aN39gv6nPTKF2luHrdDSwgCjudopu4K/LwKjQpwuaZVKB",
	"dHt1lQd7gWM/uFx79DRHSRQKKpvyYR0uHea3jXxsPmrMs2gDmtdo1F039HC418KyqMMAn5xBpsuu7jZc",
	"BqtTagU/FaFZ5YZJIayrosgV8CBvmlJ+hICEpkNU1XuVZVosbyLIHl7uzGlKxXLcrmyfwdvaRMCIuxxV",
	"g1mw3NTd+a9kOY9NpsZPHp5scMInGpPzLGbYwxMZJ8Ib6evK3zmNQfbiGAI4kelkX/RC+LdX5ObcoxWe",
	"89gJjoGxS3twDusE61YvnOzaGxv2J3XYgP2bN9OhGcPfFxlCkCj8p1tLD156SgcsYJSyygfZZZu51e/K",
	"aNs6NYcdZQVf+d2+lTUesYVoz084ChPbJwWfF7uxg9aE4XcO5dsk5I6FV4RDRsmmZ7b45pgV2qff5DQA",
	"AXaQRF6bdbRG4ZKEVxDThlMwsZMbEuaSWFlXqFplwHOrsACThXcuuFdvaZYtWzAd/LQR0pfXT4OUNsH/",
	"lqGlt90KqDfPgOoGFDCCj57mrEgr1ZX9w9VSrpcstopYqVDAQMBjPE8RJwvMo5iIAtbtysvcJm/1AEH9",
	"bHNPYoEwusSiKbTamXbuSwzbmdm20cGM4hq1WryFd1jnjycuhSRZb7kX+85Ute2az84y6Ci3+JhJknlP",
	"8oav1acr9Ty4aizNeiHhb+2GvMbUvICy77Hak9TZJRyRBQ7Xz5bTu1hOn+2ez3bPZ7vns93zjnZPV4ky",
	"iqa9n7YqnPcqoe9fcj4cszysHaKgGx9uZ711+qqHvS3Y10yEwHttFPt8kSdKVpXvbdXsY0gBqiD8CwtP",
	"KjP1qwUZNCvCmp2Zmjry+CuAGmorun93Wvv2VfuyzLs4PQeZ0GqQeSg6v3WW9AeVyzJ90EPLjo4sLyZZ",
	"kccSNErd1s4gXyqjB1GtHlMvedYxnraO0RD/7QpEv9KgDw8tYDZIvUiuddJny26j8y9qD1O7pdxfD+kE",
	"6zoPhd/H1BoaWA1JaWCN7qPey9R9SrpiEczmC3/WuUBHRW0WQek6meZGUqS3tGdrUbhPNCYDkwbpo9mt",
	"STWEJdUgCg3d1ecMnmpToBeAp4F5rjt41gfjDZh1Ulbpb4v/NxN0hf/XSMop/N+oVehuqkluNoMvleuZ",
	"OtU0fJ2H+vu55qlLgjnhn+wOteD+alNKw4kIAhualQteSpkVZborA1K14yXBETTX1Bf89w403Dmrpqo2",
	"Mc5qHPhX3xgnhzu/uYKl7D/LM3yJBXk1ZC22cftybIvXIA6HjlY54uxgChXUeJUllerMDY4Zz21iTSUu",
	"ncxm74K93Ve7e1A1KyMpzmjwLnizu7e7Z4qiASKnGk87gCctI73PiHRZVYRRSq7r6cKVDILw78NISVMm",
	"pEMeItCUSIR8z6L11mr+15Ke154RGBMQNycBbOz13qutze4pIwwr6MhYYcveutXdFXLe6mX5ZiuWP1WN",
	"bifBP/b2+tuqRi7bghnNR9Z/XtwqfscLyGNVJYQLNUKVOKbfcLndww+3mkhiIr1lTNXvCKfdtKKbudSy",
	"704BhMpxQiThotUaWDaZVhYIVsEaBbztSSui93M3JL3Vs/S1ffsoCFXCc6pUaDH9pt1rt9MiwH16ReO4",
	"XQb8RuNYuO8E3SKi8MyQQn51EF4eoQASXk19BhMXsd5q3CaqPa8KdIpI9adRkYzoLF68VAXAxGHmvqDt",
	"JqnsbU1YwMbNbtVeT4nIY+kTGDOH7JB+m1bC+mnSYf3c1jQo8iTBUPBRbdhDM7i4x1lqVeNYKs3ozhVZ",
	"AyIWpO19rRoUXmiZa4JoUN2vRGp1QB9Cd0DvwNt+ceNputa6cW0LEXk29chHhFeFqQkaiy51BRugPrj7",
	"80sKB2n3ojm4mHoUxaG+AI+wq7yte2J6wziicFl6+k2rswP1h25aMeqDppZ9M+54pcF2HKYvVJDzvesL",
	"o7kby9BjQdEWnz50najOW8bW9sVDw3o1SELs9RCKuWL/JISiOF5ns209wv8Fn3Xwju/g1t+DIYA2rgyd",
	"wq6A7zjoApKnKYvIAK1DN/Ms+rP5sB1dY1gQBNScgUrUm2scekMPdqj4dUafJggLm37T+eFvWzHzK5E6",
	"Tbape+lHzGebZX6cxDHJ6W8nY9Iswy3lr5zAm11zTanksH8SNxOnqMdgeilSan9H15E6abWqqZBrGwkn",
	"d4fJHt5UUrdBUvd0hDWSh9+aM6xXtzG4tRAANwEM8T2cXMPFSiWHSbest9U93FoTDfHiPlvvNGMUOflA",
	"NBQ5dOY0tkGj5TUZSqyhf0N9+P/El+G/87291//EWfafGWfRv4OXu+gjDpegXuA00vU1BUpyIdElQeen",
	"R4ikIYtItNsikIo8ta482rb8GXmc1Uqi3O1cayIPiHFvCDHuPeB56Pgs/rxQB83GSlg1e07PZdzmJYLc",
	"ujVvdVPguUR+T/fyAu0PeymvTNuUiJ40Yx5p+JMQVUV8Tp3CTe1i1C2oouPshgnT47KoTpdMPWBJgncE",
	"UY0UauJqhSZ0+AHi5xekspJgEpCbLIaCjSamyycizSBfaSQ67cvtIUcJvjnUH1/t7dWE2STIwaNrGgCd",
	"36vC503xdTeRqpP8JGWdm5+UFb4VWe06LVvaHu6kaPOZtAo0zZxMeeNUzDLH3kCzVk3QWe/D09f67uvw",
	"bL1plgfn5RrBna1dht0TArcuETa5BYqybt1PQxatPD81RaTa3aenADtREE+kU7ftosNqdloqdHGjCKqc",
	"2zytXJdS2kVnZ0eqCURHkhsJeUh3uxW2gghN6ak70+L2lT+zslEK4N5jKIA2/4TNqHk7eSxV1FDEg6mi",
	"Pyjf2uwJreLeKYkghsn6I91yYx6beB+fKq1LegpJCCSXWDpPDgohTVOU0DimJoVfm1ky50JnvG3aJG0g",
	"ZGdJs8Zyj/GNau2EdXYts2VZMdVlOctVleXalCLdLLumZzWf+1bsmzKinIQmj+kwdlWY/lD08oDik7bs",
	"XK51NQ2kloJe6EoaiHGkS2m8hEMgZbKMo5kY+OiAGwW/NiuOWwBklJCpFlF5CC0DGGMTHUMz37PAUgKr",
	"787tyqyyLu0AsdV6376D5CoSiWqpVb7swryosK34kq9wPHEKK06gqU5VXyYobRNhtv7MHSSYl7Mgwasr",
	"gAZsjaTRZhsbt+SLh4hoqqXq3tQU6zLyAxgKflC+z2yhVP/1Auqo1tK/D7kT6PqrD21e0Deciu4KTowQ",
	"p85t5z4x/3bvlyFtf/nOqISTOSdiSUTXRRSaVNhS3ySVikmlMNnNdfXbgWR0Wsz7OJfL6lOoKNcL9kSW",
	"mS81MVyUiCjU0yuSSYSh/m8pvV01880/+/XMxmuaYX7YmhjVkH0go8sToGBhn7cV5NudM12Xmd5A9umO",
	"T9AcUiuc/XT9Ye1GiGepPYLmnaLkfpk9I9KtbF4vSb6Lzvzld9GNFV2Ol5eWJSEM8e6iAxzHYGFYUqGU",
	"tCWLUJLHkmYxMY+m2Yrwa06leT99dnY0QQSHusIDyoXuTpAt0ODUCBSl1q9aZYyq7wwlBIvcZGG1W7Oy",
	"e6hR86wo3fP4506luHz9QbfaXHmUlPhw4WXSh7UeTM2iyoOqzjdrMahVXmzlfBKGNIsS02b0n01rh1dV",
	"w56seC/kZ+bDQ0bbwEvTOwbZ6A09nDO3/vS4C42VADD1m4Oq8gHcEIuKG8TgpKHwY1E/cNvUnmKesz0b",
	"U34sY4pTNOlOlhRZFli6ZzPKmyFt3zwZgdzL4NME33QyOdCQcV74GN6mi9JRTJYih4mBY3zzLAmevCSY",
	"tJS+lkwxIadkRSpUAkG3Jp6sJcSWQ3qd9tAxmx21rIL1VTTLYOka6185FMJ62FcCx/jGlV3PsmrbskoH",
	"3Q7SHW1Tr8gpP9bEjI8yi0fzbYw4OMv2xUPrrCZI+c56q4XXIwYibqzNlquvBnp3W8pq77A7or1daroP",
	"C5e3OsQgO9frra/BJJZuMXeVZXVwGJJMWrfEk4ty3QYpVQSSUqBsqrihz7VbSEq3KIjqrJKCbqROVHQd",
	"7nqqZNDbxqPtJygDuo8OJ5NlB5rcY2RLOJr0ts7wgqawhs/kRppsSmO6HUGo0L3qQJ5MpSMVIUuAVC7B",
	"x2YSJn6PQfC1s6czJ0D7IaO63YtAuL/Dqpo6d+PEAI3ko63JAZ7+S4oHVmBOiT6OcTpQffk+COv71YJ+",
	"AM1mqkXx9JtJin47xves68K45V4GEaM+Q96XWdjv8Xy1ud49B+Rrv3TSyF7iouT5j4vr/vjvWob7tjDw",
	"PiRvFBS+IaKfA8i/4wBy717IisRjBj2CDh7QzljOQzII+3POkjbLMIwyapd64ns2VbZXzdxMW3dY/mm6",
	"s/3Scqiuvw35WZZcHSpB25L09EnQma2Y+jgy9DCNyE1ZesMI1IJCWtkIbnz16hE+HmcL8ft8LkiL0Nob",
	"HfTxo4jVjaXfg4kaqPa8kYh5litarkBW/um3JRbL7jxfODWVFlBM0ytr0MJcl11QqMU0dTgTr4n+NlRr",
	"+1QUEbqjpPFkKl7qYdudgT1FiwZ5X17dD407Jdxb7oguXkx1dWZ/BJo3WPoBHn/cH3+sXtvIxB2epz1O",
	"QRtzp1qiFzQN4xyC+IVkWUai6ZIKyTgNcfzSR/1fXpsoytM87c2zYp4ywlSXa8RSghhHCeM2XRiQ56Ck",
	"KvYg3+w50mmeOkXbaxWVhFxDZQR1DH1PxueRABgSQnRUS4QD5PSzJWgp2WmIg70zMVHBLT9knre2p8vl",
	"Qj1MP4rlycYcP5NGU/rhuP05Kd7jyIRK0M32oye+vH6M+Ikvr5+678BA4odKoNejzG3kcxjrYXDo7Sn4",
	"GO6Z3AEio4j9abk4tkFYb9pE2IYC682jCKw3jyWwmkWrn2VXncSgZuAApdk0ROxaqRimTCvO5ZKkksJx",
	"CpGju16d2kwyVjo1NLINdb8HubaZgp0jrmyrAiy6TCBM8d87auGm1qAn/4PdnqllNmccpeRGogwvSKfq",
	"f/s9KXVlaSkAVgkpS8f2l4HViEwxTQWtjHChNO1UIiEZxwuyi2zWPnJDBRj8bfHNua5Vm2AZLtUtjkYk",
	"yZjq/NL/crUk9XtJoAd70nOMD1DayhIsmTfJ+mMNeMV9xIXatlPptS/nc4l2WwT3R70CldxiiN4WvXUB",
	"7+Md5wSYfrPlY4cFAevWuwh+UPIo4ywkJBK18vc4lHRFUMLyVIrdlpBhwzWH0e/8M94gV4NZuu0+LGTY",
	"FDWO7AY2VBG/myfNJZUYJBbVl31CtdU1s7Jgg8SmShM4/IBerFj89ebm5iVS5xFOSJcecI9ofgg596UC",
	"gJ+AXEqsjxAi2tc3SJSAT49xpANrGF+XWROMlOkWG1/MnJ+M86zTaGuw59Ksv96oU0273ZPXa1+FsvOS",
	"mecILaZbM/EdpjGwLCHIFTUIuiLxumXSooXfzW/MvGbmS8ZiglOvJ/JtG2p/IlHaIOExUhVUXF2wHqdR",
	"MQZVf0uEkSIPCDChaSdTlBL2KXPEh4JGM8MbMRWymzM89BlMffXwv5srZdfRo7CmaKIrrE21AcCZ9NQ/",
	"OJs5LELTTQ+jacSuUwhtaLN2zCQnOCmDTNQlsfcsamG7D3ayp8V+QDjAeS4gt3IqjeMJFkoidwRAvMob",
	"RXDZJU2xFqV1W4aXHexEP8GpY2irQqnj+UFH7YBlOR/IDZK5vID0fVOgDENyq8rRJVBKiL9uQe7lGBN3",
	"9MSOK6JkrDa53SPbDLEV3ZFjHi61oEZk7/FVMcv80PyqATKAW2EVfGUpP+dx8C5YSpmJd9Mpzuhuwni+",
	"S1ng2PS/lckeylwH32q1rao/2hmdnyBXhfs3eD92wMpcbWgrAN9e3P5vAAAA//+F8iU6ewwBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
