// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9W2/kNtLoXyF0zsO3gMb2XHZxdoB98HgyWW/sieG2kwNkBwEtVXdzrVtIynbvwP/9",
	"A4ukREnUpdvttmdi5CHjFq91Z7FY9TWI8rTIM8ikCN5/DQrKaQoSOP5FowiEuMivITv+qH5gWfA+KKhc",
	"BmGQ0RSC9602YcDhj5JxiIP3kpcQBiJaQkpVZ7kqVAchOcsWwf19GNCC/QSr/qHt5/VGvSpZEvcOar+u",
	"N2aWx9A7pPm43ogFXbCMSpZnJyxlUjWKQUScFeq34H1wSu9YWqYkK9Mr4CSfEyYhFUTmhIMseUYK4KSg",
	"CwhCvao/SuCrelkJjuuuIoY5LRMZvH99cBAG85ynVAbvA5bJt2+CMEj1jOZzyjLzV2iXzzIJC+Ct9X+G",
	"O4n47+7hqOQi52rJQlIuiVwCSZiQZM7ztGfZWTXcMAAFzeKr/K4XK/X39RAjgaa9g5qP646YFgmVMDBq",
	"1WCdke9VY1HkmQBk13cHB+p/UZ5JyJCiaFEkLEIs7f9H5Iiherz/y2EevA/+z34tA/b1V7H/A+c513M0",
	"UfqBxkQtEYQM7sPg3cHrx5/zsJRLyKQZlYBupyZ/+/iTf8r5FYtjyPSM7x5/xs+5JPO8zGI9498ff8aj",
	"PJsnLEKM/nUXVDQDfgPcYvLeUjmS8eGvs3NYMCH5ClUSzwvgkmkap7fiEDWO0gxxV+Ic/jojugH5CVbk",
	"+COZ55z8cHROaIOIgrDNTqEaW02cZ/5h9TdyuwQOKMnUqNyslDBBkjyiEuKeoWcQcZDV4v1z6EbuDqYv",
	"X//QHvViVYBSHtVCOwNBpqT8b2qNwZfQI79qifSb/hq20eDdoAvQetz86j+gCe0wTlk201L6J5Yk5yBQ",
	"ObVRPqcsgfgoLzOPlvxcaUcj70EQuaSS6F5K9VyzJAm6OiwM1Ie1BhYlbm5eJsmK6N6BVzm6EHNnCRub",
	"+XIfBh+UOXKSL37IvOSewA0kY1x2ki9OsN19GKQghDIJOvs5yRfEfCSWtz1EJCQU3c4zCQVhGVI9GlCk",
	"4DmSKAeluBDOqNzzBQHcio9AWQpC0tQzwYX9pADeHqgyVGIq4ZUaJRgl02qqGiShgWYF9pmkshTnQI1M",
	"a4FeI8X8VZlOv30JPZAF3bINDoEzEK6nCAO04MbQ2SSJirEDyjldDeL41OD3lslld/6QRCXnkMlkRTgU",
	"OZcsW5A8S7SQQVlseqxJGQ7DjWLGLl5h4ejssof7js4uSZRzELg03IrmwsBntw5YqqHSbRlE0giaLp4V",
	"qeSl9NNkXkpF9wKiPIsFmq24GgNJojoTOpfAye2SRUt3qUQs8zKJCdwVjMPgwg9GpYhdpU+QHnFQRHdY",
	"n8S6u4xMGznCe/o4R6QahWAnrSSm8GAYMI9GPo6VtpkzLUwVfNw53KHLknmVZ0rF9RjT1LOcUnHNssVH",
	"kJQlQvXXVnZHwNMUelbUlVz+483FEohWBga8IwO1cIq7xcXZGcxeQwddX2oEXwBND8+OjfGwGX4Pz47J",
	"NazWR62Z4APOTZPk53nw/rdhnKj1XgpFzF/CICuThF4loI81k2nFrHcKmVz7jKpzektuaFJCd8DOAAkV",
	"8lKAZ10nVBhel0smKiDeUkFKgULPC8Tmnp+Esnu366NF3dCQoCHMJiV+ZOL6FCRnkejSYAw3LPKs5yP+",
	"Tiylt4EwZwmIlZCQXngt2E/Vd6L6kv+BvcVeSOBOvgvJ3Vz8xSszlF45y5lPuZyqb6RQHy2YYoZ79jC+",
	"pMmHlbQbbPCV+kZEQSNQOuIKW7l0yjL5t3dey1MRTc+oigA3GbStZuv9hxYxHVC7C2ns1aJ6xv4Lpx88",
	"GGXimgj2X2irZ7XmU/ZhXWUXBj9kN79Q43WMY6bmoclZi7zcJfyQ3TCeZ6nSwjeUM8VnPmuhS/Y/ZDfx",
	"L8CF96BnPli6gOwmJrzMMmUqGQO4d+ww0OfdrnDOYw9dY2OC3zzg6oKo1+zTs45xuJnItb8+8Tw9TukC",
	"3PN2zNTYKcuo1HtJaVGoAfXpu09Muaf2MFhERV/DH4/OnIa8mrmnNWTAaVL1uA8tbFefjfNM7fo+DPIM",
	"Jugkd5n34XBbd6WjbdvrVPB1B+gQhQCuuPIwihSr/kv4qHGm2xDTiPxr9vNnpPEfj8524BFQWJzqEfBs",
	"x2ertuHUAUtBhbjNuUcJn5kv6nBVilr08Jqatg6BauwvnsFLAdyvgS/Nl+lL9QO1miGs4eKDaq+N0AGv",
	"Uu4Q/6IsojMOc3bngTP+joaNEnm6B7lpCkZ9QMh5ny3lzDMr59559O8PnKcY3gSeTJmFjugMSQygO+Oi",
	"zXgC2UIuPeYg/j68xD7FbBbcnCH04MUHQyVUTpiQEPceZ2nCqEddHqqfqxWb+wavnZ8wyKS+qoih4KB9",
	"msaCHTPXdW/vuEVZnfWHBGnlE7gPlSpyTJChXo6xcq+4t/cgRG6X0FDj5JYlieeMPngYgqYJMegCd5qi",
	"Ek9zvhrf0Klth30kjakc9bYbmji1zduXZGPIGzBs8PoO1oEqFcR0mgxVIRVNTtvkDNt2LtfGtmhba0+O",
	"dtkw0Vi5OfCMi2j30s69bKw4yAWbwwAOETRI3NKtBUSTzJD1raPX44ZTm+rg0aqxGK7KBd63zvMgDG4p",
	"RyWHdqNPs53kC/GRcYik10iuPjneWuN2Nz6vKzCX1AhIu4x5zm8pV79c0ega/9mZPQzuXqn2r24oqj6h",
	"OjbW86kapfHzh2pIs4FZXnLfcVT/vubSFbZzTlF1FwolAj3o05evZ71whql/PXMGvA+DUxotWQbHClnd",
	"s0RRHvJoySREsuTgd51Sp4XdaKbtf59g/kRTlqz8Q83x24RBTvPYR5lqjFR9mjrEZ69FVQ+TOd4N/1jt",
	"g0+1QWedrfnCDlw1Iu4ugKba4eGRfEBTkuJH43J3bh26Tmbn6mNYrXYuQ8wc69yHOLctl5nPQBqcRNlj",
	"qpv2ef2PdX8LlkVAoMij5V9aZ9YeRwcaOX7HqYk2aXrnTGQBxHY55sy9YDeQETUwv6HObZ4Ojhm8/mnC",
	"wS4J0RsVA/6Gzp316dEZifJszhYl14EIXW9Dj8evttRPHf3fvrxRXzZxqLx+8/98sP8Mt4NXAg91i7dg",
	"jsN90fMOWKdJfvs74jED+buewGetJvltBQKZVytZArGd98ivyugQIFWDOU0EhIRJcgVLegNWp6dAlCVS",
	"QMTmK5YtSAzZ6ucS+xzs4X/7B5bKMpC3Ob82WN6rt3yV5wlQNOBoKfMzWgpo3Arq6bthK3lK1akySVak",
	"UJ2apoa+OEK7xFzv+GaE2jU2YmhiM2UwasIetC+j4oGmpQHWxJ6fdesjhCwaexB51dcMfyc0SYhx+kZ5",
	"mpaZDf5BQduxVB1wrWcQWgoePBM1rghtCN1ffWJbkVXCbrx+USNF9x56E1jvz3Db0L3Q9m4Iav423syW",
	"XZKUQgKfBnXT2GsG5Kk3HPIIf7cD5DxagpAcfZS9t1WfrA9kJLTD2Px4hT3Vha+7zHRECKwzi6j6TJtp",
	"2kVZn1mVNo3JQZngNNWywd7zDPVS5GCvhBqRsut7D7I8pXHvTgwY14jXsY77PHNB1IB5j69dVKdMjJIY",
	"n9M0JDM7eYvL/bNon+lxJiTNIq/Esh5gZtrUzqxRzJtQjgno04EwaK9NvBcZ5r+25LDx0XjJ2N106AiP",
	"atktfNfk2GW9Jrv3IK/eWyVjmsxhRZt2nXoEHI2WEGNwjofbT5hA4aRb6SApQVjcor0qAKjHU10H+bzI",
	"0xd5uhN5CgPUPCZKJ8WzNR3WHlJ/EYMTxKCWc64MGheEPolXSVGf7HNCO9oh6bH1EIiOc0Md6pAuj84u",
	"h/i2akeq8L6J6rjqqQ/JPaEThxj00JxJu1rXjc9wLyt8QR/1m5w6UHF9IyMqyjPgEXhNCwVwNXiJEZ2F",
	"bqfDWKeMHTNxLXyhOFLHRRtc6shPGi0xAmY/rSNjpnK3GxHkjVVV8L8YDaPJNIFtgizd67I/pOazM7a9",
	"bdw4sKZB7D2U2UBtd4GeuwAHQBZ3lidnlfzquvxL0ZJ+9b01jdWRLuaUZdovHek4WP1HmS2BJnK5mujB",
	"rhdybkauf/lYz1H/eOTOVv98Wc/b2N7RkmaL7Z0qR2MF11cKLTIwA6hdnIMo06Eb2abHaFiJb8ln9MQe",
	"i/sw+OYuqOM8pcyj8j9QAUR/dN7+VL5JTudzFhEmjI+SXSWTQj8hu2lHbLcA4kZio9hCWZ3dxE2P2Hbv",
	"p7d1Yby7a9kwMDgYhCb+XHv7FCgNvrJFNccNo6Tg+d1qbxyDG9wGt69zDYv0HThfIjmegCl3EDjyDLn+",
	"JSrlJSpl46gUs/eTfOF/dahvlJsX5IRmMUlYBp3DJP7oHUd9GXq6+ETPC3HBTTj0POacMzC+w74Q9z6v",
	"YH1/vPMHoU8FVVy/+3jTQK8JaTH+brN5ZuIlhnfEOu6nI2ImHXnbiPYcexOztA7IHz5nd7oWGHHu0IWD",
	"A7NTR2pPe2hhe4zK48Yk3oCZUzfEZKpA6PfFfO56Yaa9pIiKUp3Gz6Kel6dDPpd5klPZDUDRMhOP8X0u",
	"jhgfzfS+7Ol3cKiO/ndp+A6n16Ux6DIZXOqAI2ZwUP8qT0dcL/1D/jnDptYIZnLUt0PUNS4cVDt05BKr",
	"IxuaMRr+2J2ffS+l7XUBtoCYHB1/PCdXSR5dC5JzcnxGaBxz9FFrc3bB0cjVZvoeOTT96lY0uaUrQSS9",
	"BqKwDjEoGOY3wPXAbuu9tS7WcJFn5VXCogu9gIaXxEdZMx0+RFhDApLL8xPhRI3WRw39qB4FXPNliT+k",
	"yIQk9cM1hoytDda1gJJScX2uY+/+mQvPUiwIlrmQ+FTDmKl4CLqC+qiCgTsGQCaaT3h1Rce0adjQ60Y4",
	"m/spfCiDT3J9Yc3V5fyvTC57n7E27sX6dOS0E4/Sgvcd12E1vuK9C6Cph9cw9ZnneGheHltnnVS9fQ/x",
	"xUdL0O0hfl2CXELd3Z40DAe0hnTIdDyUqG81dUqt8ZOQb4TOGcck4TJPowyw3F1byL48l+91gf/pX7sb",
	"6vFmXNhS2HeUZyZTyKz/sv1iCc6FYt3FuX1vsfsEE9eNgTn3ClRvgiPtGcDMgtp6mWT6vphpY2aahw48",
	"OLKUh1KgI7MgNW7i1utv9bPdZin8UUDTpIfpPSI6fLyk16bXbzzSfn829Hm0wefTnm7AYMDV6DkR8dJ0",
	"uSmppjrLaXzlJBcdg6YSsE7KMJM4S7Gyfs0w5Lu/qvNTjUlMC3AnpdWmXvoRrVj7UxvQq12TT6QaN38m",
	"uqm/XKF2VtDbbG1gIVE8TItu4Ksv8LgzZguaZTJBdHt1yMCTjHOyuVp57DTHSBQKKpvyYRsuA46Bjfzr",
	"Pmosi3gDmtdo1F03dHa6jvo6KfEEf7xBpsuu7jZcBmtTagM/DaHZ5IawEtZNUeQKeJQ3XSm/hoDEplNM",
	"1UeVZVosbyLIdi935ixjYrnermyfydvaRMCIh6iqySxYb+rh/FezXBVp2ctPHp7scMInlsBlkeTUwxMF",
	"B+GN8nPl75wlKHtpgsFbxHSyb9Mw9NMrckvusQoveeJcjOPYtaeqxHVimspRONm1dzbsf568Aft3T6ZT",
	"M2/iOvRNjqhudraWZrO+w5mwgLWMVV6lHB1dYCNH6UMZbVtac5oqq/jKfyHVWONJvhDnJpe590rvKUnB",
	"d7/W2YHxnj5CGM8m4TZ5dA1ccb3nzqj65rgV+qffRBugADtKPWdOjB4l0RKia4xnoRmmc4I7iEoJVtZV",
	"plYd7NgrLNBl4Z0Lz9VbmmXLHkwHP32E9Mub50FKm+B/y9DS2+4F1NsXQA0DChnBR0/zvEqQMvSO3bVS",
	"bpd5Yg2x2qDAgZDHeJkRDgvK4wREBet+42VuUxB6gKB+thnUqCCUXFHRFVr9TDv3pTccQk03H6IZxXVq",
	"tZ3BZhUPWOf3Jy6FhGI0bbp9Y6baDs1nZ5mkyi0+ZhIKrybvXDv6bKWRxxadpdlbSPxbX0PeUmZeP9i3",
	"GP3pluwSTmBBo9WL5/QhntMXv+eL3/PF7/ni93yg39M1ooyhac+nvQbno0rox5ecu2OW3fohKrrx4XY2",
	"Wu+mqext4ZvuI2g+6qM45IsyVbKqfmunZl+HFDCB+z+p8CSlVb9akGGzKuDSmalrI69/BFBDbcX2H07O",
	"3L9qX65kF6eXKBN6HTK7ovN7Z0m/MrmsU4fsWnYMZHgwiUo8nqC1zG19GeRLY7IT0+op7ZIXG+N52xgd",
	"8d9vQIwbDVp5aAGzQdo1uNXpSy27rZl7zabNY3I1Uwyo53LeEx6WOl35FVAO/JOFnKax36VbVRVpC5vV",
	"sy+lLKrKfI0BsWjpEmiMzU3Z0v//Chu+umjmhzThmGoc/NfYGGfHr35yYVD3n5UFvaICXk9Zi23cvxzb",
	"4g1ibupoDW60gylUMHMBJplU4iE4zXlp838pzDoJWN4HB3uv9w6wTEUBGS1Y8D54u3ewd4ABy3KJiNzX",
	"eHqFeNKKwhuLrctBEUoyuG3n6FREiJGqx3HwPjjLhXTIQ5jysiDkhzxeba3MZyvTaCvi2ZxWG6Vq32yx",
	"bKyn/JmvhmynsBnEjYKOTjVb32zV8vdVo7pO6nBb1chlWzzx+8j6ty/qiC/pAtNtNAkBGb9JHPtfG3W3",
	"7zWRJCC95ZfU74Rmw7Sim7nUctgq7e0WB+9xXNRN9puFwdXuWhTwbuT1s97Pw5Bk6vWOtX33JAhVwnNf",
	"aXux/1XfBNzvV7G4+1i2tFcG/MSSRLiPLdziR/hWg2FSUxReHqGAEl5NfYETV2GpP+liqS1UewKgdSar",
	"jSpkj8WXdkllexWJe4rO+koUd4u91rB+nnTY1tuaBkWZphQrLKkNe2iGVianpVY1jqXSgr26hhUiYgF9",
	"j5TUoPiYxFg0okN1P4LU5oBWQg9A78SDSWWcdW8BhnFts/97NvXEKsJrwrQEjUWXslMnmA/u/vySwkHa",
	"o1gOLqaexHBoL8Aj7BrPgJ6Z3bAeUbgsvf9Vm7MT7YdhWjHmg6aWQzPu+kaD7TjNXmgg51u3F9bmbioj",
	"jx9QH07H0HWmOm8ZW9sXD52D9iQJcTBCKObI/ychFMXxOulerwr/J37WcQY+xa2/B1MAbbyuOtNOBd/1",
	"oItI3s/yGCZYHbqZZ9GfzYft2BrT7msxNT6Wftzc4tAb2plS8duMPksQF7b/Vaexve/FzI8gdTZPU2zK",
	"j5jPNhnuehLH5NC9D9fJBomnlD9KwOeF5pjSSLX7LE4mTu7xyfRSZf78ho4jbdLqNVMxJSgRVeQNtUlO",
	"u0bqNkjqkVRYJ8fpvdFho7aNwa2FAN6L4BDfguaaLlYa6RaGZb1NQu6mxO6IF/eF7aAbo0pshKJB35bK",
	"nMxZYuPb6mMy1hwn/8aCrP+gV9G/y4ODN3+jRfGPgufxv4O/7JEfaLRE84JmsS5qJUhaCkmugFyenxDI",
	"ojyGeK9HIFXp9Fx5tG35s6Y6a2Vuf5he6yIPifFgCjEe7FAfOncWv31RimZjI6yZ6GPkMG5zpmAKwNbF",
	"WlfguUT+SOfyCu27PZQ3pu1KRDeTY/9p/E9CVA3xue/Ul+gXo27edx0SNE2Ynta5/4dk6lGepvSVANVI",
	"oSZpFpIgxx8x1HcBjZUEYQB3RYJ1pUz4iU9EmkF+Z7EY9C/3R0ek9O5Yf3x9cNASZmFQZuyPEkwDpPNH",
	"Nfi82YgeJlJ1PpK0Tsf/J2WFr1Xm00HPlvaHO9mkfC6tCk0zJ5vqeiZmnYd1olurJejs7cPzt/oeS3n2",
	"njRrxXm1Inhm65dhj4TArUuETU6Boi6v86chi16e3ze1LvqvT88RdqIinlhnmdojx80Uf0zoGgwxlha1",
	"ye64rviwRy4uTlQTDOSCOwmZMfAHDLaKCE2FjAfT4vaNP7OytQzAg6cwAO1TeZv87z58KlPUUMTOTNHv",
	"lG/tQ+9ecW9hbp6UT5D1J7rlxjwWet/JKatLetJf95aSJywjKUsSZrKN9XgB8Hme3yVpAzaHS8V2nBym",
	"ynadYG6k4L1vVQnTxcPqVdVFZQ6UIb1edZgdqFDE+iYKVFPWCzcqbhw7ULoMWdeGm8CTvYfJB7BlldBP",
	"s2T9woLyqsqlrR8fOsWNQmyqk9nWiQIfkT99wwImWnTZa8LWIIs329h6S/6yi3CdVsrcTf2MLiPv4BT8",
	"nfJ9YYuV+W1nrGXWSsM8xeDVNdB2fXbW5nvDMEMPfUQzx5R/TMy/O/j7lLZ//8aohMOcg1iCGDplYZMG",
	"W+pjkrKfmBQmy7CuQDeRjM6reZ/m5NR86BGXesGesCnzpSWGLRxq4+saCkko1uCrpTcmJr7TUvnt35SN",
	"NaxX2nkNJl4ytsSohuyOPArPgIIV7zfJdzh3sS71uIHs0x2f4Vm/Vbzy+V729J+wX6T2GjTvFAb1y+wZ",
	"SLe6aLss6B658JfAI3dWdDlXmKxOzW6Id48c0STB4/OSCWWkLfOYpGUiWZGAebyY3wC/5Uyad4wXFyeh",
	"LlKMA5ZCdwdiE6U7VYREbfWrVljKWCmYFKgoTTZEuzUru6d67C6qgqtPr3caBV7bDyvV5mpVUuPDhZdJ",
	"49OrmLqFDSed7bs50dUqv2xFPwlDmlWZRzP6n81qxydD095jeA/kF+bDLkNJ8BnlAyNI9IZ2d1PZflc7",
	"hMZGdJP6zUFV/bprikfFvaF3noP7sahfb23qTzFvtV6cKd+XM8UpXvIgT4qsC508shvl7ZS2b5+NQB5l",
	"8P2U3g0yOdKQcc37GN6mbdEhOpYip4mBU3r3IgmevSQIe4pjylwxIWdwAw0qwYhSEyzVEz/KMc1Ff1yU",
	"zVJYV6P5XXTL0fyOyPidY0Ga3YbAn9I7V3a9yKptyyodUTrJdrRNvSKn/tgSMz7KrF6E9zHi5Gy3X3Zt",
	"s5oI3AfbrRZeTxhlt7E1W6++GcU87ClrPTIeCGV2qekxPFzeLO2T/Fxvtr4Gk+C1x91Vl7egUQSFtNcS",
	"zy6Ecxuk1BBIyoCyKZumvkXuISndoiKqi0YqqDVtoqrr9KunRiarbbxIfoYyYFh1OBnlBtDkqpEt4Sgc",
	"bV3QBctwDZ/hTppUQet0O8FAmEe1gTwZA9c0hCwBMrnEOzaTuOxbjPBu6Z7BB+/9SkZ1exSB8HjKqpnC",
	"cuNX750kgL0v35//M4EdGzDnoNUxzSaaL98GYX27VtB3YNnsa1G8/9UkJ75f5+5Z12dwyy5MIkatQz7U",
	"2ZAfUb/anMseBfnGL500spe0Kj38/eJ6PLi5lWm6L8Z5DMkbRTxviOjdRkdHJRfoAPuWwqN9N6g2suf1",
	"eGCP36cSMw6RKUg/TfgqqvhY9eodOIEbSNYZ9AQ7eEA7y0sewSTsz3me9nmGcZS1dqknfmRXZX/1us2s",
	"dYfln+d1tl9aTrX1tyE/69KHUyVoXwaaMQk6s5ULn0aGHmcx3NUp8I1ArSikl43wxNfO4u7j8Xwhfp7P",
	"BfQIrbUfdHw3YnVj6bczUYNVVzcSMS9yRcsVrI2x/3VJxXI4iRXNTKFckrDs2jq0KNfVdBVqKcsczqQr",
	"0N+mWm2fqmIeD5Q0njS8Sz1s/2XgSPGQSbcvrx+Hxp1Syj1nRBcvpspxbn9EmjdY+g4efzwef9y8WSf3",
	"0mCakF/efM9Zlzrq7ZNebL3QqxXJMyA5J2nOdcYuhMSkrCZSa+rNXkzNpBHt7cIrQq6wKoHSkt+Sb/wl",
	"RdVThpbevGlGCWz/uveXN09x4fvLm+fu7DSQ+K7SWY1on42cpOu6RB16ew5O0Ucmd1vqeTqxPy+f7DYI",
	"622fCNtQYL19EoH19qkEVrfa5YvsckkMB+Q3VlaUPDGVs8T7/X1asL005+UeywNnhK91LFwdCva1ldeu",
	"+SPG7bl/NyrIuB9squ/7L/f/GwAA//+O6wruz+MAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
