// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbXW8bt9L+KwTf96IF1pbc5pwL3Tl22gqxGyN2cg4QGAa1HEmsd8ktyZUtGPrvB/zY",
	"b660ciw3OadXUXbJ4XD4zMwzs/QTjkWaCQ5cKzx5whJUJrgC+58347H5JxZcA9fmJ8myhMVEM8FHfyjB",
	"zTMVLyEl5tf/S5jjCf6/USVz5N6q0TsphcSbzSbCFFQsWWaE4Al+SyiS8GcOSuNNhN+MTw6/5mmul8C1",
	"l4rAjTOLvzn84r8LjeYi59Ss+I/XMPE1yBXIYpubyMuzZ/w2Zwm9EIt3XMu1eZBJkYHUzEFgziCh9heh",
	"lBl5JLlqjGhZthyF3FQ0FxLpJaBELBDYRSKs1xngCVZaMr4wZvAPxOwPiC0MElhBsmvDF2JxYcdtIpyC",
	"UmQBXY0uxAL5l6gwc0gDloLSJM26Em6KV0jMO1uZC5kSjSeYEg1HRkpX+ibCBuFMAsWTL7WlKrWLHUeF",
	"xW83ET5LcqVB/i4odE+GCwrT8662ZjSanof2qECuWAy/CaV75mWSrYgGtBRKI0KpBKUQ4RT5qSgTUm8R",
	"PeVKEx4HFbv2Ipgfs13Ja02kBnqqw+eBHpbA7WEYO6AHopCEBTPmAjrwWOpr6VztQlvtNPyESsKNlTx4",
	"vh1ezf4MUjHn6c2d+hcF7vzwLTvxE85EmrKA5a5FLmPjBhTQaqDsFng97EIn3tlPj1qBM24asn0wTeS2",
	"PGPK5+IlvWMIhHcjN88G4VY5C7w+YF8Ncp+/EZjlWQdWLSBVRm0dujYR0esfu/H29HCEgeepUXcJJNFL",
	"kw+oJIybHUU458Xj24D52uGgs+5ZbSmknV8U6wkZL0FpSbSQ26R/qI17sTQiReLmMg3pUBTWNfkoEqhl",
	"fSIlWf+dn/4Sdy82XfnSc1PLLkGvm0cshrp5xEH3NuwgFpZdNyQZmbGE6XURAxrO1+OTEdaQZok53Jlh",
	"2BB2U0fZO04Ze1dtamIH2+RdBxDj+uefKnMzrmEBcisldqvuOiG/UCHFGK0k3EGWbRms5ft2y4Ymq5p9",
	"KMxyExaZSdgRfiDSnKwrSkK2uRALdc4kxDqI3PJVjZUrpJdEI7UUeULRDJAEnUtuPa5QYy7kA5HmyYzE",
	"9/ZnZ/UIPx6Z8UcrIjlJzaF8aerzSyml8fhtKXIT4WvC6Uw8XohF2F62hEAPTC9RWRLYYJYwbizfxIR9",
	"GLY7499iaWMVbtqhp8iEFXA9hELXJJVTNtGAInV3wfmd1o+V6eq1ZK2GDJmsq+E6swxHucFOwZXbaeE3",
	"SlOR25iqKUjp8BmDUneWxNb+D5wGHbpSRX30baYuFhKHkmBz4VrLPNa5BBdbSk7p5JrQMoSQtOEYICI2",
	"ctnl5yRPNJ58ue30VCpTqf1X7i7aOmMvtmaN2mFegpYsDqSNLL+LRc5D7ClPZyCNxc6uPqlh+cOIyxXQ",
	"uywOSDy7+oRy6xUZyBi49tAr5M4TQWqewq0CRixl6v5OC00CaeTGPEZmBFIZsWQMzdYa2hr/801QYyva",
	"qNyV/EkBfb7gFNLtKqeQCrl+htQt2j5L5j5xKHU4GspGS9F3OWePAaU5e6xlMsaRglhwOkjzLTGutW4L",
	"mFEN9vWDqpm3gbk6Sm4DicD7GKh/Mb10nqa6rqaKUduyzoBY4F2507K9JFk9IE/PFdLCHBqTyLBKpf3p",
	"KdzZQ8uUlarB7TqGfM5ULFYg11X58NE35bt7f1Yt1aZmS8JpAhTN1haLxSeA/gLkWT22ti1CXabaRkIW",
	"uvFEvuiU75G8erPH25IgI1UmtaFppNmyH5BJqhRirRnnkun1tZHmFD3N2HtYn+Z6aat6o+ASiKlZImzo",
	"L57gfx+dXk2P3kOte0/sLPe9gfkmnGba1FD4UsgcvaMLQKdXUxzhVVF/4vHxyfHYKC0y4CRjeIJ/Ph4f",
	"jw1/IHpp9Rm5von5uYBA6vnNvkbxEuJ7bCVJ+71kSsuXZ/5d43vWT+5jS1OYh7kt0VUeGwYzzxOzrU1U",
	"aDJKSbz0/HunRrYC8hOQKirPXiUvvegX01VLMp87ejBMVz8BZVI8rrepeuMlf72qq5NRAZmgjhY6qgwi",
	"Lnu4VkBTu88nU1dOhjR6ka9q7VZz6Ptaub9kXZacrvFT1736uhlar9zAyAyqPg1uH2sGVTYtQ/0orRKX",
	"N3DbbmWeuyzzSEYkSUGDNPVuhz0AScswLh64qnNvy05s4PgzB1vX+LihgaS2pVOFJC1ziGrG7xQ7nQqM",
	"Kd1Ohj+k5BGdjMc/9qzrx94xyz76Fy8Dbl+FWATV2wNCLEg5BuOsPALXSihO3qJtPARt4wMis8o3FlL1",
	"TPPl1hhV5WlK5BpP8K+gW9TGRdI80SxLmlDTZKFa3KbrA0/+5/R8Myoquu3OcOGqrpYfWHyZ5NSB1/7I",
	"PpSP2BYo44sa/x7QFjMcPWVJwiqiHlIwzqWyDcNKoQ6fTxlnaZ7iyTjE7Z869PbRjEa8LEt3dO9CaiXM",
	"d4FLrUrGdTIeB0rc1K3qX+/SOLQkLfuR0UDfbnYxA6b4hSUapKHBtuNiv/SgH1y3BQmJXLvlx2M0nSMu",
	"NFIZxGzOgEbePgqRJLH2O+4xVL1JtFdEajbaXiMGNvj14BBYy0SuIfPdBT+b46pSoLmbZ8S7wfl/YPa/",
	"LnNvgbEXCoh7kIwDUgwbPm3sNCHRNjK2h8Si57klIu6Ogu843WdN4HTPFb/WYffpaladjBZz2o/GfN/8",
	"xZzmkQJTbTdIDKlheJsvu4rniBbdmJEpIlRvmWSXrG5VoHLejpop1PRR+KXAQpLkw9yaa2BdhTe3z4aN",
	"yX31SxnqrwRDebTtc9x5xCN7b8R2lIK3Hy6JvK8uOSQkBoUEdzUmUah262TIWZ/bxVzEBKXfCrp+uUS+",
	"s6G4abaoTLDeDGkpNABgA7AhjtYE5f4PGDX85eBdY998Q6C6Z0nSj6n3LEnKKyoDkWPm/DcBx1rob9DU",
	"QVO/x7KVQLbO61fQHxpTX4N89N1z+6p80rTAt0MuWnePGoVB/zkXF5HUyF7LUaMn+++Arkjny8eg3oiX",
	"vj8hzyTERFfDQxy4vn93VWz/bovb1NeWDFNO4bG8glC0X8qbT70tF3ffZwmoUKSH7Yv5XEFPeyPY3Nir",
	"AXPQftGA4mg/bd9xeihddxZV/8uNrde7cderWPFnMYO7bf4vgg7arOr/JLxXy6qIAPX7kt9d2XsT2ESV",
	"l8rkY/LRpnz+VIaKTt4yQGg2lUxNd7v5TwAAAP//SEWWgKo4AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
