// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb32/bOPL/Vwh+vw+7gBI7u7178FuadHeNJtugSXsHFEFAS2ObG4nUkpQTI/D/fuAP",
	"SZRE2XIaZ9u7faorkTPDmc/8FPOEY57lnAFTEk+esACZcybB/OfNeKz/iTlTwJT+SfI8pTFRlLPRH5Iz",
	"/UzGS8iI/vX/AuZ4gv9vVNMc2bdy9E4ILvBms4lwAjIWNNdE8AS/JQkS8GcBUuFNhN+MTw7P87RQS2DK",
	"UUVg12nmbw7P/Heu0JwXLNEc//EaKr4GsQJRHnMTOXrGxm8LmiYXfPGOKbHWD3LBcxCKWgjMKaSJ+UWS",
	"hGp6JL1qrGhptlqF7FY05wKpJaCULxAYJhFW6xzwBEslKFtoNbgHfPYHxAYGKawg3XXgC764MOs2Ec5A",
	"SrKArkQXfIHcS1SqOSQBzUAqkuVdCjflK8TnnaPMuciIwhOcEAVHmkqX+ibCGuFUQIInXzxWtdjliaNS",
	"47ebCJ+lhVQgfucJdC3DeALT8660ejWanofOKEGsaAy/cal69uWCrogCtORSIZIkAqREhCXIbUU5F2oL",
	"6SmTirA4KNi1I0Hdmu1CXisiFCSnKmwP9LAEZoyh9YAeiEQCFlSrC5KBZvF5qULuQptnDbehpnBjKA/e",
	"b5bXuz+DkNR6evOk7kWJO7d8y0nchjOeZTSguWteiFi7QQJoNZB2C7wOdiGLd87TI1bAxk1Ftg3TRG7L",
	"M6Zszl/SO4ZAeDdyi3wQbqXVwOsD9tUg9/kbgVmRd2DVAlKt1JbRlY6ITv7YrjfWwxEGVmRa3CWQVC11",
	"PkgEoUyfKMIFKx/fBtTXDgcdvmceK6SsX5T8uIiXIJUgiott1D94614sjQie2r1UQTYUhb4kH3kKXtYn",
	"QpD13/npL3H38tC1Lz03tewi9Lp5xGCom0csdG/DDmJg2XVDkpMZTalalzGg4Xw9PhlhBVmeauPOdIUN",
	"YTe1JXvHKWPnqk1JzGKTvH0AUaZ+/qlWN2UKFiC2lsSW6y4LOUYlFa20quAOVtmmgjX1vjmyLpOlp58E",
	"ZoUOi1Qn7Ag/EKEta5uSkG4u+EKeUwGxCiK3euVV5RKpJVFILnmRJmgGSIAqBDMeV4ox5+KBCP1kRuJ7",
	"87PDPcKPR3r90YoIRjJtlC9NeX6pqDQev61IbiJ8TVgy448XfBHWl2kh0ANVS1S1BCaYpZRpzTcxYR6G",
	"9U7Zt9jaGIGbeuhpMmEFTA0poT1K1ZZNNKBJ3d1wfqf9Y606v5f0esiQyroSrnNT4Ui72Aqol6MfpEp4",
	"oRAXSKoEhPjRcyX7TodZ8yroxTV/+dHNlroASC00ghOFayWKWBUCbECpCklLV8eTIVVIG4OB6sOEK8N+",
	"TopU4cmX284gpdaP3J9zl2nLsI6spw3PgpegBI0DuSIv7mJesFDJVGQzEFpjZ1ef5LCkockVEpK7PA5Q",
	"PLv6hArjCjmIGJhyeCvpzlNOPPdgRgBNNqHy/k5xRQK540Y/RnoFkjkxFRiarRW0Jf7nm6DEhrQWuUv5",
	"k4Tk+YQzyLaLnEHGxfoZVLdI+yya+wSfzOJoaAlakb4rGH0MCM3oo5e+KEMSYs6SQZJvCWwtvi1gRh7s",
	"fUN56m1gzkfJbSD6Ox8D+S+qltbTZNfVZLlqW6oZEAucK3fmtJck96Pw9FwixbXRqEC6lJTKWU/izhla",
	"qqxFDR7XlsXnVMZ8BWJd9wwf3SS+e/ZnNVDtemxJWJJCgmZrg8Vy7t/fdTxrsNbWRWi05B0kpKEbV72X",
	"4/E9kldv9nhbVcVIVkltaBppzukHZJI6hRhtxoWgan2tqVlBT3P6HtanhVqaVl4LuASiG5UI65oXT/C/",
	"j06vpkfvwRvZE7PLfmSgbvKmqNKNE77kokDvkgWg06spjvCqbDrx+PjkeKyF5jkwklM8wT8fj4/Husgl",
	"amnkGdlhif65gEDq+c28RvES4ntsKAnzkWSaVC/P3LvGR6yf7BeWJjEHc9OXyyKOQcp5kepjbaJSklFG",
	"4qUrundKZNoetwHJst3sFfLSkX4xWZUg87ktD4bJ6jagXPDH9TZRbxzlrxd1dTIqIROU0UBHVkHEZg/b",
	"/zel+3wytT1kSKIX+ZTWni+HPqpV50vXVZ9ppz2+7PUnzRC/6gAjvaj+Hrh9rV5U67QK9aOsTlxOwW29",
	"VXnussojOREkAwVCN7md6gFIVoVx/sCkX3ub6sQEjj8LMM2MixsKSGbmOHVIUqKAyFN+p8PptF1UqnYy",
	"/CEjj+hkPP6xh69be0dN9dHPvAq4fW1hGVRvDwixYMkxGGeVCez8oLS8Qdt4CNrGB0RmnW8MpPxM8+VW",
	"K1UWWUbEGk/wr6BapY2NpEWqaJ42oabIQrZqm64PPLmf0/PNqOzotjvDhe26Wn5g8KWTUwde+yP7UD5i",
	"5p6ULbz6e8AsTNfoGU1TWhfqIQHjQkgzJawF6tTzGWU0KzI8GYdq+6dOefuoVyNWtaU7RnYhsVLqRr+V",
	"VFXFdTIeB1rczHJ1r3dJHGKZVEPIaKBvN0eXAVX8QlMFQpfBdsyiRQnMWo7RdI4YV0jmENM5hSRy+pGI",
	"pKnR33GPovzJ0F4RqTlde40Y2KivB4dALxPZgcx3F/xMjqtbgeZpnhHvBuf/gdn/usq9JcZeKCDuUWQc",
	"sMQw4dPETh0SzSBje0g0X+u3R8TdUfAdS/bhCSzZk+PXOuw+U816ktGqnPYrY77v+kVb80iC7rYbRQzx",
	"MLzNl23Hc5SU05iRbiJkb5tkWNZXKVC1b0fPFBr6SPxSYCFp+mFu1DWwr8Kb22fDRuc+/yaG/CvBUJm2",
	"bcedJh6ZyyJmohS88nBJxH19syElMUjEme0xiUTeVZMhtj43zGzEBKne8mT9col850Bx0xxR6WC9GTJS",
	"aADABGBdOBoVVOc/YNRwN4J3rX3zDYHqnqZpP6be0zSt7qUMRI7e898EHKOhv0Hjg8a/vLK1gGzZ61dQ",
	"HxpbX6P46Lvc9lX5pKmBb6e4aF04ajQG/XYubx/JkbmLI0dP5t8BU5HOl49BsxFHff+CPBcQE1UvD9XA",
	"/vnt/bD9py32UF/bMkxZAo/VFYRy/FJdd+odudhLPktApSA91T6fzyX0jDeCw429BjAHnRcNaI72k/Yd",
	"Sw4l686m6n95sPV61+x6BSv/FmbwtM39GdBBh1X9n4T3GlmVEcC/JPndtb03gUPUealKPjofbarnT1Wo",
	"6OQtDYTmUEn3dLeb/wQAAP//uz8+4p84AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
