// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W/bOBL/VwjePdwBSu3s9u7Bb2mS2zWabIMm7R1QBAEtji1uJFJLUkmMwP/7gR/6",
	"pmw5TbLtXZ/iSNTMcOY3n+QjjkWWCw5cKzx7xBJULrgC+8/b6dT8iQXXwLX5SfI8ZTHRTPDJ70pw80zF",
	"CWTE/PqrhCWe4b9MapoT91ZNTqUUEm82mwhTULFkuSGCZ/gdoUjCHwUojTcRfjs9fHmeR4VOgGtPFYFb",
	"Z5i/fXnmvwmNlqLg1HD8x2uo+BLkHchym5vI07M2flewlJ6J1SnXcm0e5FLkIDVzEFgySKn9RShlhh5J",
	"L1orOpqtViH3KVoKiXQCKBUrBJZJhPU6BzzDSkvGV0YN/oFY/A6xhUEKd5Du2vCZWJ3ZdZsIZ6AUWUFf",
	"ojOxQv4lKtUckoBloDTJ8j6Fq/IVEsveVpZCZkTjGaZEw4Gh0qe+ibBBOJNA8exLg1UtdrnjqNT49SbC",
	"x2mhNMjfBIW+ZbigMD/pS2tWo/lJaI8K5B2L4Veh9MB3uWR3RANKhNKIUCpBKUQ4Rf5TlAupt5Cec6UJ",
	"j4OCXXoSzK/ZLuSlJlIDPdJhe6D7BLg1htEDuicKSVgxoy6gI83S5KULtQttDWv4D2oKV5by6O/t8vrr",
	"zyAVc57e3ql/UeLOL9+yE//BscgyFtDcpShkbNyAArobSbsDXg+7kMV7+xkQK2DjtiK7hmkjt+MZc74U",
	"z+kdYyC8G7lFPgq3ymng9QH7apD7/I3ArMh7sOoAqVZqx+jaREQvf+zWW+vhCAMvMiNuAiTVickHVBLG",
	"zY4iXPDy8XVAfd1w0ON73GCFtPOLkp+QcQJKS6KF3Eb9Q2Pds6URKVL3LdOQjUVhU5KPIoVG1idSkvWP",
	"/PSnuHu56dqXnppadhF63TxiMdTPIw6612EHsbDsuyHJyYKlTK/LGNByvgGfjLCGLE+NcRemwoawm7qS",
	"veeUsXfVtiR2sU3eTQAxrn/+qVY34xpWILeWxI7rLgt5RiUVo7Sq4N4eJBXhdCEeGrqhsChMSGQmWUf4",
	"nkhjVdeQhPRyJlbqhEmIdRC11atGRa6QTohGKhFFStECkARdSG69rRRjKeQ9kebJgsS39mePe4QfDsz6",
	"gzsiOcmMQb605flXRaX1+F1FchPhS6eCM7EKdyS2fUD3TCeoagdsIEsZN1pv48E+DNIxb77BtsYK3NbD",
	"kxvMH81ipVXfItZNY6NZrDWtPvohTl/bqbNDsHW/1LKIdSGBOnfqOfOodN81eCDNG+qO/ZIUqcazL9e9",
	"iYWjYgXZn3OfaUepnmxDGw0NnoOWLA4E5by4iUXBQ7VJkS1AGo0dX3xS46KzIVcooDd5HKB4fPEJFRaG",
	"OcgYuPb2LukuU0Ea0ORWAEOWMnV7o4UmgSB9ZR4jswKpnNhSBy3WGroS//NtUGJL2ojcp/xJAX064Qyy",
	"7SJnkAm5fgLVLdI+ieY+jp85HI2t9SrSNwVnDwGhOXto5ArGkYJYcDpK8i1BpcO3A8yoAfumoRrqbWGu",
	"iZLrQKj2Pgbq30wnztNU39VUuWpbXhgRC7wr9wai58RaybNB8xOFtDBGYxKZmk1pbz2Fe3voqLIWNbhd",
	"V3+eMBWLO5Drujj/6Efe/b0/qVPpFj8J4TQFihZri8VywD5c3j9pgtXVRWiG09hISENXvkwu59B7JK/B",
	"7GFpuSSmqqQ2No20B+IjMkmdQqw240Iyvb401JygRzl7D+ujQie2ZzYCJkBMRxBhU2DiGf7PwdHF/OA9",
	"NGbjxH7lpvnMj7g006ZDwedCFuiUrgAdXcxxhO/K7g5P3xy+mRqhRQ6c5AzP8M9vpm+mpqIkOrHyTNxU",
	"wvxcQSD1/GpfoziB+BZbStKeRsxp9fLYv2udFv3kjjLaxDzMbQOsijgGpZZFara1iUpJJhmJE1/h7pTI",
	"nif4D5Aq+7pBIc896WeTVUuyXLryYJys/gOUS/Gw3ibqlaf89aLeHU5KyARltNBRVRBx2cM12m3pPh/O",
	"XcMWkuhZzqy6g9zQ6VW1v3RdNXVurNKUvT47DPGrNjAxi+qDt+1rzaJap1Won2R14vIK7uqtynPnVR7J",
	"iSQZaJCmo+xVD0CyKoyLe66atbetTmzg+KMA20j4uKGBZHZgUockLQuIGsrvdRe9locp3U2Gf8vIAzqc",
	"Tv8+wNevvWG2+hhmXgXcoR6uDKrXLwixYMkxGmeVCVyzXlreom06Bm3TF0RmnW8spJqZ5su1UaoqsoyY",
	"thv/ArpT2rhIWqSa5WkbapqsVKe26fvAo/85P9lMyo5uuzOcua6r4wcWXyY59eC1P7JfykfsgJHxVaP+",
	"HjF4MjV6xtKU1YV6SMC4kMqO42qBevV8xjjLigzPpqHa/rFX3j6Y1YhXbemO+VhIrJT5GWslVVVxHU6n",
	"gRY3c1z9610Sh1jSauIXjfTt9pxwkHA5OBlN1E+KXiMutWre0WGpkR3ckOS7C0g279TleXs3T4hBo3Py",
	"yIx8WeXD0kGeKUjtkfhfMO3bkGbjmQlTdriwPUzZo+rtUWp3ZDrldB+ewOmeHL/WYfeZNNbThU41s19p",
	"8X3XFMaaBwpMB9wqLEgDw9t82XUhB7SckExMYa8GWxfLsr5HgKrvdvQxoUGMws8FFpKmH5ZWXSN7Hby5",
	"fjJsSJq2riGoPxMMlWm7dtxp4om9KWGnPMHz/nMib+tj/ZTEoJDgru8jCjXuWYyx9Yll5iImKP1O0PXz",
	"JfKdQ75Ne2xkgvVmTJvfAoANwKaYsyqo9v+CUcNfh9219u03BKpblqbDmHrP0rS6lDESOeab/yXgWA39",
	"AE0TNM2bG1sLyI69fgH9ofXpaxQfQze7viqftDXw7RQXnds2rcZg2M7l1Rs1sXdv1OTR/h0xqeidRoya",
	"V3jq+xfkuYSY6Hp5qAZu7t9djtp/AuI29bUtw5xTeKiuBZQjkUV52DI4BnG3XBJApSAD1b5YLhUMjByC",
	"A4e9hiIvOsMZ0RztJ+0ppy8l686m6v952PR698y+r2HV8DHtXiOrMgLUUeM7bHuvApuo81KVfEw+2lTP",
	"H6tQ0ctbBgjtoZLp6a43/w0AAP//XsTpu5w3AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
